///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AnimalsDetailsDataNotes {
/*
{
  "id": 1,
  "text": "Sint ullam cum quos aliquam nihil eum id in velit quisquam dolor error cupiditate qui qui voluptates laudantium soluta nisi veritatis beatae doloremque sequi excepturi incidunt aut occaecati pariatur laboriosam est officiis et eaque id qui animi eos doloribus aliquam assumenda ea tempore et blanditiis tempore consequatur optio totam voluptates alias tenetur itaque eum sint id qui minus perferendis tempora libero consequatur pariatur reprehenderit consectetur tenetur ex sed sapiente qui sed error eum incidunt et eum facere possimus voluptatem est autem impedit est porro aut vel est autem numquam ex fugiat officiis perferendis est consequatur est eos voluptas cupiditate odio eos nesciunt magni ipsum.",
  "created_at": "2021-09-14 23:42:54"
}
*/

  String? id;
  String? text;
  String? createdAt;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataNotes({
    this.id,
    this.text,
    this.createdAt,
  });

  AnimalsDetailsDataNotes.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    text = json["text"]?.toString();
    createdAt = json["created_at"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["text"] = text;
    data["created_at"] = createdAt;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataDocuments {
/*
{
  "id": 309,
  "url": "https://api.thepaws.app/storage/media/309/aaaa.pdf",
  "name": "aaaa",
  "file_name": "aaaa.pdf",
  "type": "pdf"
}
*/

  String? id;
  String? url;
  String? name;
  String? fileName;
  String? type;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataDocuments({
    this.id,
    this.url,
    this.name,
    this.fileName,
    this.type,
  });

  AnimalsDetailsDataDocuments.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    url = json["url"]?.toString();
    name = json["name"]?.toString();
    fileName = json["file_name"]?.toString();
    type = json["type"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["url"] = url;
    data["name"] = name;
    data["file_name"] = fileName;
    data["type"] = type;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataMotherImageConversionsMedium {
/*
{
  "url": "https://api.thepaws.app/storage/media/308/conversions/821084-medium.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataMotherImageConversionsMedium({
    this.url,
  });

  AnimalsDetailsDataMotherImageConversionsMedium.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataMotherImageConversionsSmall {
/*
{
  "url": "https://api.thepaws.app/storage/media/308/conversions/821084-small.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataMotherImageConversionsSmall({
    this.url,
  });

  AnimalsDetailsDataMotherImageConversionsSmall.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataMotherImageConversionsLarge {
/*
{
  "url": "https://api.thepaws.app/storage/media/308/conversions/821084-large.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataMotherImageConversionsLarge({
    this.url,
  });

  AnimalsDetailsDataMotherImageConversionsLarge.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataMotherImageConversions {
/*
{
  "large": {
    "url": "https://api.thepaws.app/storage/media/308/conversions/821084-large.jpg"
  },
  "small": {
    "url": "https://api.thepaws.app/storage/media/308/conversions/821084-small.jpg"
  },
  "medium": {
    "url": "https://api.thepaws.app/storage/media/308/conversions/821084-medium.jpg"
  }
}
*/

  AnimalsDetailsDataMotherImageConversionsLarge? large;
  AnimalsDetailsDataMotherImageConversionsSmall? small;
  AnimalsDetailsDataMotherImageConversionsMedium? medium;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataMotherImageConversions({
    this.large,
    this.small,
    this.medium,
  });

  AnimalsDetailsDataMotherImageConversions.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    large = (json["large"] != null && (json["large"] is Map))
        ? AnimalsDetailsDataMotherImageConversionsLarge.fromJson(json["large"])
        : null;
    small = (json["small"] != null && (json["small"] is Map))
        ? AnimalsDetailsDataMotherImageConversionsSmall.fromJson(json["small"])
        : null;
    medium = (json["medium"] != null && (json["medium"] is Map))
        ? AnimalsDetailsDataMotherImageConversionsMedium.fromJson(
            json["medium"])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (large != null) {
      data["large"] = large!.toJson();
    }
    if (small != null) {
      data["small"] = small!.toJson();
    }
    if (medium != null) {
      data["medium"] = medium!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataMotherImage {
/*
{
  "id": 308,
  "conversions": {
    "large": {
      "url": "https://api.thepaws.app/storage/media/308/conversions/821084-large.jpg"
    },
    "small": {
      "url": "https://api.thepaws.app/storage/media/308/conversions/821084-small.jpg"
    },
    "medium": {
      "url": "https://api.thepaws.app/storage/media/308/conversions/821084-medium.jpg"
    }
  },
  "file_name": "821084.jpg"
}
*/

  String? id;
  AnimalsDetailsDataMotherImageConversions? conversions;
  String? fileName;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataMotherImage({
    this.id,
    this.conversions,
    this.fileName,
  });

  AnimalsDetailsDataMotherImage.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    conversions = (json["conversions"] != null && (json["conversions"] is Map))
        ? AnimalsDetailsDataMotherImageConversions.fromJson(json["conversions"])
        : null;
    fileName = json["file_name"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (conversions != null) {
      data["conversions"] = conversions!.toJson();
    }
    data["file_name"] = fileName;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataFatherImageConversionsMedium {
/*
{
  "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-medium.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataFatherImageConversionsMedium({
    this.url,
  });

  AnimalsDetailsDataFatherImageConversionsMedium.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataFatherImageConversionsSmall {
/*
{
  "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-small.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataFatherImageConversionsSmall({
    this.url,
  });

  AnimalsDetailsDataFatherImageConversionsSmall.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataFatherImageConversionsLarge {
/*
{
  "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-large.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataFatherImageConversionsLarge({
    this.url,
  });

  AnimalsDetailsDataFatherImageConversionsLarge.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataFatherImageConversions {
/*
{
  "large": {
    "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-large.jpg"
  },
  "small": {
    "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-small.jpg"
  },
  "medium": {
    "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-medium.jpg"
  }
}
*/

  AnimalsDetailsDataFatherImageConversionsLarge? large;
  AnimalsDetailsDataFatherImageConversionsSmall? small;
  AnimalsDetailsDataFatherImageConversionsMedium? medium;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataFatherImageConversions({
    this.large,
    this.small,
    this.medium,
  });

  AnimalsDetailsDataFatherImageConversions.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    large = (json["large"] != null && (json["large"] is Map))
        ? AnimalsDetailsDataFatherImageConversionsLarge.fromJson(json["large"])
        : null;
    small = (json["small"] != null && (json["small"] is Map))
        ? AnimalsDetailsDataFatherImageConversionsSmall.fromJson(json["small"])
        : null;
    medium = (json["medium"] != null && (json["medium"] is Map))
        ? AnimalsDetailsDataFatherImageConversionsMedium.fromJson(
            json["medium"])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (large != null) {
      data["large"] = large!.toJson();
    }
    if (small != null) {
      data["small"] = small!.toJson();
    }
    if (medium != null) {
      data["medium"] = medium!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataFatherImage {
/*
{
  "id": 307,
  "conversions": {
    "large": {
      "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-large.jpg"
    },
    "small": {
      "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-small.jpg"
    },
    "medium": {
      "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-medium.jpg"
    }
  },
  "file_name": "d31c5457afbfcbb382cf56a849b992ba.jpg"
}
*/

  String? id;
  AnimalsDetailsDataFatherImageConversions? conversions;
  String? fileName;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataFatherImage({
    this.id,
    this.conversions,
    this.fileName,
  });

  AnimalsDetailsDataFatherImage.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    conversions = (json["conversions"] != null && (json["conversions"] is Map))
        ? AnimalsDetailsDataFatherImageConversions.fromJson(json["conversions"])
        : null;
    fileName = json["file_name"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (conversions != null) {
      data["conversions"] = conversions!.toJson();
    }
    data["file_name"] = fileName;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataImagesConversionsMedium {
/*
{
  "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-medium.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataImagesConversionsMedium({
    this.url,
  });

  AnimalsDetailsDataImagesConversionsMedium.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataImagesConversionsSmall {
/*
{
  "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-small.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataImagesConversionsSmall({
    this.url,
  });

  AnimalsDetailsDataImagesConversionsSmall.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataImagesConversionsLarge {
/*
{
  "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-large.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataImagesConversionsLarge({
    this.url,
  });

  AnimalsDetailsDataImagesConversionsLarge.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataImagesConversions {
/*
{
  "large": {
    "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-large.jpg"
  },
  "small": {
    "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-small.jpg"
  },
  "medium": {
    "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-medium.jpg"
  }
}
*/

  AnimalsDetailsDataImagesConversionsLarge? large;
  AnimalsDetailsDataImagesConversionsSmall? small;
  AnimalsDetailsDataImagesConversionsMedium? medium;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataImagesConversions({
    this.large,
    this.small,
    this.medium,
  });

  AnimalsDetailsDataImagesConversions.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    large = (json["large"] != null && (json["large"] is Map))
        ? AnimalsDetailsDataImagesConversionsLarge.fromJson(json["large"])
        : null;
    small = (json["small"] != null && (json["small"] is Map))
        ? AnimalsDetailsDataImagesConversionsSmall.fromJson(json["small"])
        : null;
    medium = (json["medium"] != null && (json["medium"] is Map))
        ? AnimalsDetailsDataImagesConversionsMedium.fromJson(json["medium"])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (large != null) {
      data["large"] = large!.toJson();
    }
    if (small != null) {
      data["small"] = small!.toJson();
    }
    if (medium != null) {
      data["medium"] = medium!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataImages {
/*
{
  "id": 303,
  "conversions": {
    "large": {
      "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-large.jpg"
    },
    "small": {
      "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-small.jpg"
    },
    "medium": {
      "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-medium.jpg"
    }
  },
  "file_name": "5484d9d1eab8ea3017b17e29.jpg"
}
*/

  String? id;
  AnimalsDetailsDataImagesConversions? conversions;
  String? fileName;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataImages({
    this.id,
    this.conversions,
    this.fileName,
  });

  AnimalsDetailsDataImages.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    conversions = (json["conversions"] != null && (json["conversions"] is Map))
        ? AnimalsDetailsDataImagesConversions.fromJson(json["conversions"])
        : null;
    fileName = json["file_name"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (conversions != null) {
      data["conversions"] = conversions!.toJson();
    }
    data["file_name"] = fileName;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataAvatarConversionsMedium {
/*
{
  "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-medium.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataAvatarConversionsMedium({
    this.url,
  });

  AnimalsDetailsDataAvatarConversionsMedium.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataAvatarConversionsSmall {
/*
{
  "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-small.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataAvatarConversionsSmall({
    this.url,
  });

  AnimalsDetailsDataAvatarConversionsSmall.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataAvatarConversionsLarge {
/*
{
  "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-large.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataAvatarConversionsLarge({
    this.url,
  });

  AnimalsDetailsDataAvatarConversionsLarge.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataAvatarConversions {
/*
{
  "large": {
    "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-large.jpg"
  },
  "small": {
    "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-small.jpg"
  },
  "medium": {
    "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-medium.jpg"
  }
}
*/

  AnimalsDetailsDataAvatarConversionsLarge? large;
  AnimalsDetailsDataAvatarConversionsSmall? small;
  AnimalsDetailsDataAvatarConversionsMedium? medium;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataAvatarConversions({
    this.large,
    this.small,
    this.medium,
  });

  AnimalsDetailsDataAvatarConversions.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    large = (json["large"] != null && (json["large"] is Map))
        ? AnimalsDetailsDataAvatarConversionsLarge.fromJson(json["large"])
        : null;
    small = (json["small"] != null && (json["small"] is Map))
        ? AnimalsDetailsDataAvatarConversionsSmall.fromJson(json["small"])
        : null;
    medium = (json["medium"] != null && (json["medium"] is Map))
        ? AnimalsDetailsDataAvatarConversionsMedium.fromJson(json["medium"])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (large != null) {
      data["large"] = large!.toJson();
    }
    if (small != null) {
      data["small"] = small!.toJson();
    }
    if (medium != null) {
      data["medium"] = medium!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataAvatar {
/*
{
  "id": 302,
  "conversions": {
    "large": {
      "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-large.jpg"
    },
    "small": {
      "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-small.jpg"
    },
    "medium": {
      "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-medium.jpg"
    }
  },
  "file_name": "meeting-new-dogs.jpg"
}
*/

  String? id;
  AnimalsDetailsDataAvatarConversions? conversions;
  String? fileName;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataAvatar({
    this.id,
    this.conversions,
    this.fileName,
  });

  AnimalsDetailsDataAvatar.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    conversions = (json["conversions"] != null && (json["conversions"] is Map))
        ? AnimalsDetailsDataAvatarConversions.fromJson(json["conversions"])
        : null;
    fileName = json["file_name"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (conversions != null) {
      data["conversions"] = conversions!.toJson();
    }
    data["file_name"] = fileName;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataOfferPrice {
/*
{
  "value": "0.00",
  "currency": "USD",
  "formatted": "$0.00"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataOfferPrice({
    this.value,
    this.currency,
    this.formatted,
  });

  AnimalsDetailsDataOfferPrice.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataOfferType {
/*
{
  "id": "adoption",
  "desc": "تبني"
}
*/

  String? id;
  String? desc;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataOfferType({
    this.id,
    this.desc,
  });

  AnimalsDetailsDataOfferType.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    desc = json["desc"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["desc"] = desc;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataOffer {
/*
{
  "id": 1,
  "type": {
    "id": "adoption",
    "desc": "تبني"
  },
  "is_active": true,
  "description": "Quo qui consequatur impedit in praesentium similique voluptatem. Quo atque quam vero laborum consequatur a autem eum. Quasi qui iste quidem dicta sint deleniti laudantium. Velit voluptatem blanditiis aut quae consequuntur ut.",
  "price": {
    "value": "0.00",
    "currency": "USD",
    "formatted": "$0.00"
  }
}
*/

  String? id;
  AnimalsDetailsDataOfferType? type;
  bool? isActive;
  String? description;
  AnimalsDetailsDataOfferPrice? price;
  Map<String, dynamic> __origJson = {};
  String? desc;

  AnimalsDetailsDataOffer({
    this.id,
    this.type,
    this.isActive,
    this.description,
    this.price,
  });

  AnimalsDetailsDataOffer.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    type = (json["type"] != null && (json["type"] is Map))
        ? AnimalsDetailsDataOfferType.fromJson(json["type"])
        : null;
    isActive = json["is_active"];

    desc = json["desc"]?.toString() ?? json["description"]?.toString();

    description = json["description"]?.toString();
    price = (json["price"] != null && (json["price"] is Map))
        ? AnimalsDetailsDataOfferPrice.fromJson(json["price"])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (type != null) {
      data["type"] = type!.toJson();
    }

    data["desc"] = desc;

    data["is_active"] = isActive;
    data["description"] = description;
    if (price != null) {
      data["price"] = price!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataHybridSpecies {
/*
{
  "id": 2,
  "name": "Voluptas aspernatur voluptatem dolor.",
  "animal_type": "cat",
  "is_hybrid": true
}
*/

  String? id;
  String? name;
  String? animalType;
  bool? isHybrid;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataHybridSpecies({
    this.id,
    this.name,
    this.animalType,
    this.isHybrid,
  });

  AnimalsDetailsDataHybridSpecies.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    animalType = json["animal_type"]?.toString();
    isHybrid = json["is_hybrid"];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["animal_type"] = animalType;
    data["is_hybrid"] = isHybrid;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataSpecies {
/*
{
  "id": 16,
  "name": "Consectetur expedita dicta ut totam dolorum dignissimos dolore.",
  "animal_type": "dog",
  "is_hybrid": false
}
*/

  String? id;
  String? name;
  String? animalType;
  bool? isHybrid;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataSpecies({
    this.id,
    this.name,
    this.animalType,
    this.isHybrid,
  });

  AnimalsDetailsDataSpecies.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    name = json["name"]?.toString();
    animalType = json["animal_type"]?.toString();
    isHybrid = json["is_hybrid"];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["animal_type"] = animalType;
    data["is_hybrid"] = isHybrid;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataColorPattern {
/*
{
  "id": 3,
  "name": "Gray"
}
*/

  String? id;
  String? name;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataColorPattern({
    this.id,
    this.name,
  });

  AnimalsDetailsDataColorPattern.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    name = json["desc"]?.toString() ?? json["name"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataColor {
/*
{
  "id": 3,
  "name": "رمادي"
}
*/

  String? id;
  String? name;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataColor({
    this.id,
    this.name,
  });

  AnimalsDetailsDataColor.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    name = json["name"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreederUserAvatarConversionsMedium {
/*
{
  "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-medium.png"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreederUserAvatarConversionsMedium({
    this.url,
  });

  AnimalsDetailsDataBreederUserAvatarConversionsMedium.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreederUserAvatarConversionsSmall {
/*
{
  "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-small.png"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreederUserAvatarConversionsSmall({
    this.url,
  });

  AnimalsDetailsDataBreederUserAvatarConversionsSmall.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreederUserAvatarConversionsLarge {
/*
{
  "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-large.png"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreederUserAvatarConversionsLarge({
    this.url,
  });

  AnimalsDetailsDataBreederUserAvatarConversionsLarge.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreederUserAvatarConversions {
/*
{
  "large": {
    "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-large.png"
  },
  "small": {
    "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-small.png"
  },
  "medium": {
    "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-medium.png"
  }
}
*/

  AnimalsDetailsDataBreederUserAvatarConversionsLarge? large;
  AnimalsDetailsDataBreederUserAvatarConversionsSmall? small;
  AnimalsDetailsDataBreederUserAvatarConversionsMedium? medium;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreederUserAvatarConversions({
    this.large,
    this.small,
    this.medium,
  });

  AnimalsDetailsDataBreederUserAvatarConversions.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    large = (json["large"] != null && (json["large"] is Map))
        ? AnimalsDetailsDataBreederUserAvatarConversionsLarge.fromJson(
            json["large"])
        : null;
    small = (json["small"] != null && (json["small"] is Map))
        ? AnimalsDetailsDataBreederUserAvatarConversionsSmall.fromJson(
            json["small"])
        : null;
    medium = (json["medium"] != null && (json["medium"] is Map))
        ? AnimalsDetailsDataBreederUserAvatarConversionsMedium.fromJson(
            json["medium"])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (large != null) {
      data["large"] = large!.toJson();
    }
    if (small != null) {
      data["small"] = small!.toJson();
    }
    if (medium != null) {
      data["medium"] = medium!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreederUserAvatar {
/*
{
  "id": 42,
  "conversions": {
    "large": {
      "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-large.png"
    },
    "small": {
      "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-small.png"
    },
    "medium": {
      "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-medium.png"
    }
  },
  "file_name": "avatar.png"
}
*/

  String? id;
  AnimalsDetailsDataBreederUserAvatarConversions? conversions;
  String? fileName;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreederUserAvatar({
    this.id,
    this.conversions,
    this.fileName,
  });

  AnimalsDetailsDataBreederUserAvatar.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    conversions = (json["conversions"] != null && (json["conversions"] is Map))
        ? AnimalsDetailsDataBreederUserAvatarConversions.fromJson(
            json["conversions"])
        : null;
    fileName = json["file_name"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (conversions != null) {
      data["conversions"] = conversions!.toJson();
    }
    data["file_name"] = fileName;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreederUserUsernameType {
/*
{
  "id": "mobile",
  "desc": "رقم موبايل"
}
*/

  String? id;
  String? desc;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreederUserUsernameType({
    this.id,
    this.desc,
  });

  AnimalsDetailsDataBreederUserUsernameType.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    desc = json["desc"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["desc"] = desc;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreederUserUserType {
/*
{
  "id": 3,
  "desc": "مقدم خدمة"
}
*/

  String? id;
  String? desc;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreederUserUserType({
    this.id,
    this.desc,
  });

  AnimalsDetailsDataBreederUserUserType.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    desc = json["desc"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["desc"] = desc;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreederUserName {
/*
{
  "first": "Ms. Cecile Walsh V",
  "last": "Collins",
  "full": "Ms. Cecile Walsh V Collins"
}
*/

  String? first;
  String? last;
  String? full;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreederUserName({
    this.first,
    this.last,
    this.full,
  });

  AnimalsDetailsDataBreederUserName.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    first = json["first"]?.toString();
    last = json["last"]?.toString();
    full = json["full"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["first"] = first;
    data["last"] = last;
    data["full"] = full;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreederUserStatus {
/*
{
  "id": "active",
  "desc": "نشط"
}
*/

  String? id;
  String? desc;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreederUserStatus({
    this.id,
    this.desc,
  });

  AnimalsDetailsDataBreederUserStatus.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    desc = json["desc"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["desc"] = desc;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreederUser {
/*
{
  "id": 42,
  "status": {
    "id": "active",
    "desc": "نشط"
  },
  "name": {
    "first": "Ms. Cecile Walsh V",
    "last": "Collins",
    "full": "Ms. Cecile Walsh V Collins"
  },
  "user_type": {
    "id": 3,
    "desc": "مقدم خدمة"
  },
  "username_type": {
    "id": "mobile",
    "desc": "رقم موبايل"
  },
  "avatar": {
    "id": 42,
    "conversions": {
      "large": {
        "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-large.png"
      },
      "small": {
        "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-small.png"
      },
      "medium": {
        "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-medium.png"
      }
    },
    "file_name": "avatar.png"
  }
}
*/

  String? id;
  AnimalsDetailsDataBreederUserStatus? status;
  AnimalsDetailsDataBreederUserName? name;
  AnimalsDetailsDataBreederUserUserType? userType;
  AnimalsDetailsDataBreederUserUsernameType? usernameType;
  AnimalsDetailsDataBreederUserAvatar? avatar;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreederUser({
    this.id,
    this.status,
    this.name,
    this.userType,
    this.usernameType,
    this.avatar,
  });

  AnimalsDetailsDataBreederUser.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    status = (json["status"] != null && (json["status"] is Map))
        ? AnimalsDetailsDataBreederUserStatus.fromJson(json["status"])
        : null;
    name = (json["name"] != null && (json["name"] is Map))
        ? AnimalsDetailsDataBreederUserName.fromJson(json["name"])
        : null;
    userType = (json["user_type"] != null && (json["user_type"] is Map))
        ? AnimalsDetailsDataBreederUserUserType.fromJson(json["user_type"])
        : null;
    usernameType =
        (json["username_type"] != null && (json["username_type"] is Map))
            ? AnimalsDetailsDataBreederUserUsernameType.fromJson(
                json["username_type"])
            : null;
    avatar = (json["avatar"] != null && (json["avatar"] is Map))
        ? AnimalsDetailsDataBreederUserAvatar.fromJson(json["avatar"])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (status != null) {
      data["status"] = status!.toJson();
    }
    if (name != null) {
      data["name"] = name!.toJson();
    }
    if (userType != null) {
      data["user_type"] = userType!.toJson();
    }
    if (usernameType != null) {
      data["username_type"] = usernameType!.toJson();
    }
    if (avatar != null) {
      data["avatar"] = avatar!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreederContacts {
/*
{
  "whatsappSameAsMobile": false,
  "whatsapp": "9647901355212",
  "viberSameAsMobile": false,
  "viber": "9647901879899"
}
*/

  bool? whatsappSameAsMobile;
  String? whatsapp;

  bool? viberSameAsMobile;
  String? viber;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreederContacts({
    this.whatsappSameAsMobile,
    this.whatsapp,
    this.viberSameAsMobile,
    this.viber,
  });

  AnimalsDetailsDataBreederContacts.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    whatsappSameAsMobile = json["whatsappSameAsMobile"];
    whatsapp = json["whatsapp"]?.toString();
    viberSameAsMobile = json["viberSameAsMobile"];
    viber = json["viber"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["whatsappSameAsMobile"] = whatsappSameAsMobile;
    data["whatsapp"] = whatsapp;
    data["viberSameAsMobile"] = viberSameAsMobile;
    data["viber"] = viber;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreederAccountType {
/*
{
  "id": "service_provider",
  "desc": "مقدم خدمة"
}
*/

  String? id;
  String? desc;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreederAccountType({
    this.id,
    this.desc,
  });

  AnimalsDetailsDataBreederAccountType.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    desc = json["desc"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["desc"] = desc;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataBreeder {
/*
{
  "id": 42,
  "mobile": "9647901749470",
  "account_type": {
    "id": "service_provider",
    "desc": "مقدم خدمة"
  },
  "contacts": {
    "whatsappSameAsMobile": false,
    "whatsapp": "9647901355212",
    "viberSameAsMobile": false,
    "viber": "9647901879899"
  },
  "user": {
    "id": 42,
    "status": {
      "id": "active",
      "desc": "نشط"
    },
    "name": {
      "first": "Ms. Cecile Walsh V",
      "last": "Collins",
      "full": "Ms. Cecile Walsh V Collins"
    },
    "user_type": {
      "id": 3,
      "desc": "مقدم خدمة"
    },
    "username_type": {
      "id": "mobile",
      "desc": "رقم موبايل"
    },
    "avatar": {
      "id": 42,
      "conversions": {
        "large": {
          "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-large.png"
        },
        "small": {
          "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-small.png"
        },
        "medium": {
          "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-medium.png"
        }
      },
      "file_name": "avatar.png"
    }
  }
}
*/

  String? id;
  String? mobile;

  String getViber() {
    if (contacts?.viber != null && (contacts?.viber?.length ?? 0) > 0) {
      return contacts?.viber ?? '';
    }

    if (contacts?.viberSameAsMobile ?? false) {
      return mobile ?? '';
    }

    return '';
  }

  String getWhatsapp() {
    if (contacts?.whatsapp != null && (contacts?.whatsapp?.length ?? 0) > 0) {
      return contacts?.whatsapp ?? '';
    }

    if (contacts?.whatsappSameAsMobile ?? false) {
      return mobile ?? '';
    }

    return '';
  }

  AnimalsDetailsDataBreederAccountType? accountType;
  AnimalsDetailsDataBreederContacts? contacts;
  AnimalsDetailsDataBreederUser? user;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataBreeder({
    this.id,
    this.mobile,
    this.accountType,
    this.contacts,
    this.user,
  });

  AnimalsDetailsDataBreeder.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    mobile = json["mobile"]?.toString();
    accountType = (json["account_type"] != null &&
            (json["account_type"] is Map))
        ? AnimalsDetailsDataBreederAccountType.fromJson(json["account_type"])
        : null;
    contacts = (json["contacts"] != null && (json["contacts"] is Map))
        ? AnimalsDetailsDataBreederContacts.fromJson(json["contacts"])
        : null;
    user = (json["user"] != null && (json["user"] is Map))
        ? AnimalsDetailsDataBreederUser.fromJson(json["user"])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["mobile"] = mobile;
    if (accountType != null) {
      data["account_type"] = accountType!.toJson();
    }
    if (contacts != null) {
      data["contacts"] = contacts!.toJson();
    }
    if (user != null) {
      data["user"] = user!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataReactions {
/*
{
  "is_favorited": false
}
*/

  bool? isFavorited;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataReactions({
    this.isFavorited,
  });

  AnimalsDetailsDataReactions.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    isFavorited = json["is_favorited"];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["is_favorited"] = isFavorited;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataPropertiesHairStyle {
/*
{
  "id": "long_hair",
  "desc": "شعر طويل"
}
*/

  String? id;
  String? desc;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataPropertiesHairStyle({
    this.id,
    this.desc,
  });

  AnimalsDetailsDataPropertiesHairStyle.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    desc = json["desc"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["desc"] = desc;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataProperties {
/*
{
  "is_hybrid": false,
  "is_sterilized": true,
  "hair_style": {
    "id": "long_hair",
    "desc": "شعر طويل"
  }
}
*/

  bool? isHybrid;
  bool? isSterilized;
  AnimalsDetailsDataPropertiesHairStyle? hairStyle;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataProperties({
    this.isHybrid,
    this.isSterilized,
    this.hairStyle,
  });

  AnimalsDetailsDataProperties.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    isHybrid = json["is_hybrid"];
    isSterilized = json["is_sterilized"];
    hairStyle = (json["hair_style"] != null && (json["hair_style"] is Map))
        ? AnimalsDetailsDataPropertiesHairStyle.fromJson(json["hair_style"])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["is_hybrid"] = isHybrid;
    data["is_sterilized"] = isSterilized;
    if (hairStyle != null) {
      data["hair_style"] = hairStyle!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataAge {
/*
{
  "friendly": "2 years and 11 months"
}
*/

  String? friendly;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataAge({
    this.friendly,
  });

  AnimalsDetailsDataAge.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    friendly = json["friendly"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["friendly"] = friendly;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataGender {
/*
{
  "id": "female",
  "desc": "انثى"
}
*/

  String? id;
  String? desc;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataGender({
    this.id,
    this.desc,
  });

  AnimalsDetailsDataGender.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    desc = json["desc"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["desc"] = desc;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataType {
/*
{
  "id": "dog",
  "desc": "كلب"
}
*/

  String? id;
  String? desc;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataType({
    this.id,
    this.desc,
  });

  AnimalsDetailsDataType.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    desc = json["desc"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["desc"] = desc;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsDataStatus {
/*
{
  "id": "adoption",
  "desc": "تبني"
}
*/

  String? id;
  String? desc;
  Map<String, dynamic> __origJson = {};

  AnimalsDetailsDataStatus({
    this.id,
    this.desc,
  });

  AnimalsDetailsDataStatus.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    desc = json["desc"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["desc"] = desc;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetailsData {
/*
{
  "id": 1,
  "code": "CON 1",
  "status": {
    "id": "adoption",
    "desc": "تبني"
  },
  "type": {
    "id": "dog",
    "desc": "كلب"
  },
  "name": "Officia dolorum.",
  "gender": {
    "id": "female",
    "desc": "انثى"
  },
  "birth_date": "2018-09-22",
  "share_url": "https://api.thepaws.app",
  "age": {
    "friendly": "2 years and 11 months"
  },
  "properties": {
    "is_hybrid": false,
    "is_sterilized": true,
    "hair_style": {
      "id": "long_hair",
      "desc": "شعر طويل"
    }
  },
  "extra_description": "Voluptates rem velit praesentium facere qui inventore qui. Eos molestias quasi et a tempora saepe. Quasi commodi et quia repellendus. Cupiditate temporibus ut magni illo. Nostrum quia hic qui quae eaque vel. Eaque aut aliquid quos velit ea necessitatibus. Ullam illo et ut perferendis maxime et dolores. Ut eius occaecati alias enim. Veniam quae ut totam et maiores debitis sint.",
  "reactions": {
    "is_favorited": false
  },
  "breeder": {
    "id": 42,
    "mobile": "9647901749470",
    "account_type": {
      "id": "service_provider",
      "desc": "مقدم خدمة"
    },
    "contacts": {
      "whatsappSameAsMobile": false,
      "whatsapp": "9647901355212",
      "viberSameAsMobile": false,
      "viber": "9647901879899"
    },
    "user": {
      "id": 42,
      "status": {
        "id": "active",
        "desc": "نشط"
      },
      "name": {
        "first": "Ms. Cecile Walsh V",
        "last": "Collins",
        "full": "Ms. Cecile Walsh V Collins"
      },
      "user_type": {
        "id": 3,
        "desc": "مقدم خدمة"
      },
      "username_type": {
        "id": "mobile",
        "desc": "رقم موبايل"
      },
      "avatar": {
        "id": 42,
        "conversions": {
          "large": {
            "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-large.png"
          },
          "small": {
            "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-small.png"
          },
          "medium": {
            "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-medium.png"
          }
        },
        "file_name": "avatar.png"
      }
    }
  },
  "color": {
    "id": 3,
    "name": "رمادي"
  },
  "color_pattern": {
    "id": 3,
    "name": "Gray"
  },
  "species": {
    "id": 16,
    "name": "Consectetur expedita dicta ut totam dolorum dignissimos dolore.",
    "animal_type": "dog",
    "is_hybrid": false
  },
  "hybrid_species": {
    "id": 2,
    "name": "Voluptas aspernatur voluptatem dolor.",
    "animal_type": "cat",
    "is_hybrid": true
  },
  "offer": {
    "id": 1,
    "type": {
      "id": "adoption",
      "desc": "تبني"
    },
    "is_active": true,
    "description": "Quo qui consequatur impedit in praesentium similique voluptatem. Quo atque quam vero laborum consequatur a autem eum. Quasi qui iste quidem dicta sint deleniti laudantium. Velit voluptatem blanditiis aut quae consequuntur ut.",
    "price": {
      "value": "0.00",
      "currency": "USD",
      "formatted": "$0.00"
    }
  },
  "avatar": {
    "id": 302,
    "conversions": {
      "large": {
        "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-large.jpg"
      },
      "small": {
        "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-small.jpg"
      },
      "medium": {
        "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-medium.jpg"
      }
    },
    "file_name": "meeting-new-dogs.jpg"
  },
  "images": [
    {
      "id": 303,
      "conversions": {
        "large": {
          "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-large.jpg"
        },
        "small": {
          "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-small.jpg"
        },
        "medium": {
          "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-medium.jpg"
        }
      },
      "file_name": "5484d9d1eab8ea3017b17e29.jpg"
    }
  ],
  "father_image": {
    "id": 307,
    "conversions": {
      "large": {
        "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-large.jpg"
      },
      "small": {
        "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-small.jpg"
      },
      "medium": {
        "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-medium.jpg"
      }
    },
    "file_name": "d31c5457afbfcbb382cf56a849b992ba.jpg"
  },
  "mother_image": {
    "id": 308,
    "conversions": {
      "large": {
        "url": "https://api.thepaws.app/storage/media/308/conversions/821084-large.jpg"
      },
      "small": {
        "url": "https://api.thepaws.app/storage/media/308/conversions/821084-small.jpg"
      },
      "medium": {
        "url": "https://api.thepaws.app/storage/media/308/conversions/821084-medium.jpg"
      }
    },
    "file_name": "821084.jpg"
  },
  "documents": [
    {
      "id": 309,
      "url": "https://api.thepaws.app/storage/media/309/aaaa.pdf",
      "name": "aaaa",
      "file_name": "aaaa.pdf",
      "type": "pdf"
    }
  ],
  "notes": [
    {
      "id": 1,
      "text": "Sint ullam cum quos aliquam nihil eum id in velit quisquam dolor error cupiditate qui qui voluptates laudantium soluta nisi veritatis beatae doloremque sequi excepturi incidunt aut occaecati pariatur laboriosam est officiis et eaque id qui animi eos doloribus aliquam assumenda ea tempore et blanditiis tempore consequatur optio totam voluptates alias tenetur itaque eum sint id qui minus perferendis tempora libero consequatur pariatur reprehenderit consectetur tenetur ex sed sapiente qui sed error eum incidunt et eum facere possimus voluptatem est autem impedit est porro aut vel est autem numquam ex fugiat officiis perferendis est consequatur est eos voluptas cupiditate odio eos nesciunt magni ipsum.",
      "created_at": "2021-09-14 23:42:54"
    }
  ]
}
*/

  dynamic video;
  String? id;
  String? code;
  AnimalsDetailsDataStatus? status;
  AnimalsDetailsDataType? type;
  String? name;
  AnimalsDetailsDataGender? gender;
  String? birthDate;
  String? shareUrl;
  AnimalsDetailsDataAge? age;
  AnimalsDetailsDataProperties? properties;
  String? extraDescription;
  AnimalsDetailsDataReactions? reactions;
  AnimalsDetailsDataBreeder? breeder;
  AnimalsDetailsDataColor? color;
  AnimalsDetailsDataColorPattern? colorPattern;
  AnimalsDetailsDataSpecies? species;
  AnimalsDetailsDataHybridSpecies? hybridSpecies;
  AnimalsDetailsDataOffer? offer;
  AnimalsDetailsDataAvatar? avatar;
  List<AnimalsDetailsDataImages?>? images;
  AnimalsDetailsDataFatherImage? fatherImage;
  AnimalsDetailsDataMotherImage? motherImage;
  List<AnimalsDetailsDataDocuments>? documents;
  List<AnimalsDetailsDataNotes?>? notes;
  Map<String, dynamic> __origJson = {};

  getMedia() {
    List result = [];
    if (video != null) {
      result.add({'url': video['url'], 'id': video['id'], 'type': 'video'});
    }

    if (avatar != null) {
      result.add({
        'url': avatar?.conversions?.large?.url,
        'id': avatar?.id,
        'type': 'image'
      });
    }

    result.addAll((images ?? [])
        .map((e) =>
            {'url': e?.conversions!.large!.url, 'id': e?.id, 'type': 'image'})
        .toList());

    return result;
  }

  AnimalsDetailsData({
    this.id,
    this.code,
    this.status,
    this.type,
    this.video,
    this.name,
    this.gender,
    this.birthDate,
    this.shareUrl,
    this.age,
    this.properties,
    this.extraDescription,
    this.reactions,
    this.breeder,
    this.color,
    this.colorPattern,
    this.species,
    this.hybridSpecies,
    this.offer,
    this.avatar,
    this.images,
    this.fatherImage,
    this.motherImage,
    this.documents,
    this.notes,
  });

  AnimalsDetailsData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();

    video = json["video"];

    code = json["code"]?.toString();
    status = (json["status"] != null && (json["status"] is Map))
        ? AnimalsDetailsDataStatus.fromJson(json["status"])
        : null;
    type = (json["type"] != null && (json["type"] is Map))
        ? AnimalsDetailsDataType.fromJson(json["type"])
        : null;
    name = json["name"]?.toString();
    gender = (json["gender"] != null && (json["gender"] is Map))
        ? AnimalsDetailsDataGender.fromJson(json["gender"])
        : null;
    birthDate = json["birth_date"]?.toString();
    shareUrl = json["share_url"]?.toString();
    age = (json["age"] != null && (json["age"] is Map))
        ? AnimalsDetailsDataAge.fromJson(json["age"])
        : null;
    properties = (json["properties"] != null && (json["properties"] is Map))
        ? AnimalsDetailsDataProperties.fromJson(json["properties"])
        : null;
    extraDescription = json["extra_description"]?.toString();
    reactions = (json["reactions"] != null && (json["reactions"] is Map))
        ? AnimalsDetailsDataReactions.fromJson(json["reactions"])
        : null;
    breeder = (json["breeder"] != null && (json["breeder"] is Map))
        ? AnimalsDetailsDataBreeder.fromJson(json["breeder"])
        : null;
    color = (json["color"] != null && (json["color"] is Map))
        ? AnimalsDetailsDataColor.fromJson(json["color"])
        : null;
    colorPattern =
        (json["color_pattern"] != null && (json["color_pattern"] is Map))
            ? AnimalsDetailsDataColorPattern.fromJson(json["color_pattern"])
            : null;
    species = (json["species"] != null && (json["species"] is Map))
        ? AnimalsDetailsDataSpecies.fromJson(json["species"])
        : null;
    hybridSpecies =
        (json["hybrid_species"] != null && (json["hybrid_species"] is Map))
            ? AnimalsDetailsDataHybridSpecies.fromJson(json["hybrid_species"])
            : null;
    offer = (json["offer"] != null && (json["offer"] is Map))
        ? AnimalsDetailsDataOffer.fromJson(json["offer"])
        : null;
    avatar = (json["avatar"] != null && (json["avatar"] is Map))
        ? AnimalsDetailsDataAvatar.fromJson(json["avatar"])
        : null;
    if (json["images"] != null && (json["images"] is List)) {
      final v = json["images"];
      final arr0 = <AnimalsDetailsDataImages>[];
      v.forEach((v) {
        arr0.add(AnimalsDetailsDataImages.fromJson(v));
      });
      images = arr0;
    }
    fatherImage =
        (json["father_image"] != null && (json["father_image"] is Map))
            ? AnimalsDetailsDataFatherImage.fromJson(json["father_image"])
            : null;
    motherImage =
        (json["mother_image"] != null && (json["mother_image"] is Map))
            ? AnimalsDetailsDataMotherImage.fromJson(json["mother_image"])
            : null;
    if (json["documents"] != null && (json["documents"] is List)) {
      final v = json["documents"];
      final arr0 = <AnimalsDetailsDataDocuments>[];
      v.forEach((v) {
        arr0.add(AnimalsDetailsDataDocuments.fromJson(v));
      });
      documents = arr0;
    }
    if (json["notes"] != null && (json["notes"] is List)) {
      final v = json["notes"];
      final arr0 = <AnimalsDetailsDataNotes>[];
      v.forEach((v) {
        arr0.add(AnimalsDetailsDataNotes.fromJson(v));
      });
      notes = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["code"] = code;
    data["video"] = video;

    if (status != null) {
      data["status"] = status!.toJson();
    }
    if (type != null) {
      data["type"] = type!.toJson();
    }
    data["name"] = name;
    if (gender != null) {
      data["gender"] = gender!.toJson();
    }
    data["birth_date"] = birthDate;
    data["share_url"] = shareUrl;
    if (age != null) {
      data["age"] = age!.toJson();
    }
    if (properties != null) {
      data["properties"] = properties!.toJson();
    }
    data["extra_description"] = extraDescription;
    if (reactions != null) {
      data["reactions"] = reactions!.toJson();
    }
    if (breeder != null) {
      data["breeder"] = breeder!.toJson();
    }
    if (color != null) {
      data["color"] = color!.toJson();
    }
    if (colorPattern != null) {
      data["color_pattern"] = colorPattern!.toJson();
    }
    if (species != null) {
      data["species"] = species!.toJson();
    }
    if (hybridSpecies != null) {
      data["hybrid_species"] = hybridSpecies!.toJson();
    }
    if (offer != null) {
      data["offer"] = offer!.toJson();
    }
    if (avatar != null) {
      data["avatar"] = avatar!.toJson();
    }
    if (images != null) {
      final v = images;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["images"] = arr0;
    }
    if (fatherImage != null) {
      data["father_image"] = fatherImage!.toJson();
    }
    if (motherImage != null) {
      data["mother_image"] = motherImage!.toJson();
    }
    if (documents != null) {
      final v = documents;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data["documents"] = arr0;
    }
    if (notes != null) {
      final v = notes;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["notes"] = arr0;
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class AnimalsDetails {
/*
{
  "data": {
    "id": 1,
    "code": "CON 1",
    "status": {
      "id": "adoption",
      "desc": "تبني"
    },
    "type": {
      "id": "dog",
      "desc": "كلب"
    },
    "name": "Officia dolorum.",
    "gender": {
      "id": "female",
      "desc": "انثى"
    },
    "birth_date": "2018-09-22",
    "share_url": "https://api.thepaws.app",
    "age": {
      "friendly": "2 years and 11 months"
    },
    "properties": {
      "is_hybrid": false,
      "is_sterilized": true,
      "hair_style": {
        "id": "long_hair",
        "desc": "شعر طويل"
      }
    },
    "extra_description": "Voluptates rem velit praesentium facere qui inventore qui. Eos molestias quasi et a tempora saepe. Quasi commodi et quia repellendus. Cupiditate temporibus ut magni illo. Nostrum quia hic qui quae eaque vel. Eaque aut aliquid quos velit ea necessitatibus. Ullam illo et ut perferendis maxime et dolores. Ut eius occaecati alias enim. Veniam quae ut totam et maiores debitis sint.",
    "reactions": {
      "is_favorited": false
    },
    "breeder": {
      "id": 42,
      "mobile": "9647901749470",
      "account_type": {
        "id": "service_provider",
        "desc": "مقدم خدمة"
      },
      "contacts": {
        "whatsappSameAsMobile": false,
        "whatsapp": "9647901355212",
        "viberSameAsMobile": false,
        "viber": "9647901879899"
      },
      "user": {
        "id": 42,
        "status": {
          "id": "active",
          "desc": "نشط"
        },
        "name": {
          "first": "Ms. Cecile Walsh V",
          "last": "Collins",
          "full": "Ms. Cecile Walsh V Collins"
        },
        "user_type": {
          "id": 3,
          "desc": "مقدم خدمة"
        },
        "username_type": {
          "id": "mobile",
          "desc": "رقم موبايل"
        },
        "avatar": {
          "id": 42,
          "conversions": {
            "large": {
              "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-large.png"
            },
            "small": {
              "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-small.png"
            },
            "medium": {
              "url": "https://api.thepaws.app/storage/media/42/conversions/avatar-medium.png"
            }
          },
          "file_name": "avatar.png"
        }
      }
    },
    "color": {
      "id": 3,
      "name": "رمادي"
    },
    "color_pattern": {
      "id": 3,
      "name": "Gray"
    },
    "species": {
      "id": 16,
      "name": "Consectetur expedita dicta ut totam dolorum dignissimos dolore.",
      "animal_type": "dog",
      "is_hybrid": false
    },
    "hybrid_species": {
      "id": 2,
      "name": "Voluptas aspernatur voluptatem dolor.",
      "animal_type": "cat",
      "is_hybrid": true
    },
    "offer": {
      "id": 1,
      "type": {
        "id": "adoption",
        "desc": "تبني"
      },
      "is_active": true,
      "description": "Quo qui consequatur impedit in praesentium similique voluptatem. Quo atque quam vero laborum consequatur a autem eum. Quasi qui iste quidem dicta sint deleniti laudantium. Velit voluptatem blanditiis aut quae consequuntur ut.",
      "price": {
        "value": "0.00",
        "currency": "USD",
        "formatted": "$0.00"
      }
    },
    "avatar": {
      "id": 302,
      "conversions": {
        "large": {
          "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-large.jpg"
        },
        "small": {
          "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-small.jpg"
        },
        "medium": {
          "url": "https://api.thepaws.app/storage/media/302/conversions/meeting-new-dogs-medium.jpg"
        }
      },
      "file_name": "meeting-new-dogs.jpg"
    },
    "images": [
      {
        "id": 303,
        "conversions": {
          "large": {
            "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-large.jpg"
          },
          "small": {
            "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-small.jpg"
          },
          "medium": {
            "url": "https://api.thepaws.app/storage/media/303/conversions/5484d9d1eab8ea3017b17e29-medium.jpg"
          }
        },
        "file_name": "5484d9d1eab8ea3017b17e29.jpg"
      }
    ],
    "father_image": {
      "id": 307,
      "conversions": {
        "large": {
          "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-large.jpg"
        },
        "small": {
          "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-small.jpg"
        },
        "medium": {
          "url": "https://api.thepaws.app/storage/media/307/conversions/d31c5457afbfcbb382cf56a849b992ba-medium.jpg"
        }
      },
      "file_name": "d31c5457afbfcbb382cf56a849b992ba.jpg"
    },
    "mother_image": {
      "id": 308,
      "conversions": {
        "large": {
          "url": "https://api.thepaws.app/storage/media/308/conversions/821084-large.jpg"
        },
        "small": {
          "url": "https://api.thepaws.app/storage/media/308/conversions/821084-small.jpg"
        },
        "medium": {
          "url": "https://api.thepaws.app/storage/media/308/conversions/821084-medium.jpg"
        }
      },
      "file_name": "821084.jpg"
    },
    "documents": [
      {
        "id": 309,
        "url": "https://api.thepaws.app/storage/media/309/aaaa.pdf",
        "name": "aaaa",
        "file_name": "aaaa.pdf",
        "type": "pdf"
      }
    ],
    "notes": [
      {
        "id": 1,
        "text": "Sint ullam cum quos aliquam nihil eum id in velit quisquam dolor error cupiditate qui qui voluptates laudantium soluta nisi veritatis beatae doloremque sequi excepturi incidunt aut occaecati pariatur laboriosam est officiis et eaque id qui animi eos doloribus aliquam assumenda ea tempore et blanditiis tempore consequatur optio totam voluptates alias tenetur itaque eum sint id qui minus perferendis tempora libero consequatur pariatur reprehenderit consectetur tenetur ex sed sapiente qui sed error eum incidunt et eum facere possimus voluptatem est autem impedit est porro aut vel est autem numquam ex fugiat officiis perferendis est consequatur est eos voluptas cupiditate odio eos nesciunt magni ipsum.",
        "created_at": "2021-09-14 23:42:54"
      }
    ]
  }
}
*/

  AnimalsDetailsData? data;
  Map<String, dynamic> __origJson = {};

  AnimalsDetails({
    this.data,
  });

  AnimalsDetails.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    data = (json["data"] != null && (json["data"] is Map))
        ? AnimalsDetailsData.fromJson(json["data"])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
