/// languages : [{"id":"en","name":"English","native":"English","direction":"ltr"},{"id":"ar","name":"Arabic","native":"???????","direction":"rtl"},{"id":"ku","name":"Kurdish","native":"?????","direction":"rtl"}]
/// currencies : [{"id":"USD","name":{"ar":"??????? ????????","en":"United States dollar","ku":"??????? ????????"},"parts":100,"symbol":"$"}]
/// governorates : [{"id":1,"name":"?????"},{"id":2,"name":"?????"},{"id":3,"name":"??????????"},{"id":4,"name":"???????"},{"id":5,"name":"????"},{"id":6,"name":"??????"},{"id":7,"name":"?? ???"},{"id":8,"name":"????????"},{"id":9,"name":"?????"},{"id":10,"name":"????"},{"id":11,"name":"?????"},{"id":12,"name":"??????"},{"id":13,"name":"?????"},{"id":14,"name":"?????"},{"id":15,"name":"??????"},{"id":16,"name":" ?????"},{"id":17,"name":"?????"},{"id":18,"name":"???? ?????"},{"id":19,"name":"????"}]
/// colors : [{"id":1,"name":"????"},{"id":2,"name":"????"},{"id":3,"name":"?????"},{"id":4,"name":"???"}]
/// about_app : {"about_us":" ","info":{"info_email":"info@paws.com","info_mobile":"9647901911601","info_whats":"9647901911601"},"social_networks":{"socials_facebook":"https://facebook.com","socials_twitter":"https://twitter.com","socials_instagram":"https://instagram.com"}}
/// enums : {"account_types":[{"id":"breeder","value":"????"},{"id":"service_provider","value":"???? ????"}],"username_types":[{"id":"email","value":"???? ????????"},{"id":"mobile","value":"??? ??????"},{"id":"facebook","value":"??????"},{"id":"google","value":"????"}],"enquiry_types":[{"id":"enquiry","value":"???????"},{"id":"request","value":"???"},{"id":"complaint","value":"????"},{"id":"other","value":"????"}],"animal_types":[{"id":"dog","value":"???"},{"id":"cat","value":"??"}],"article_tags":[{"id":1,"name":"?????"},{"id":2,"name":"?????"},{"id":3,"name":"???????"},{"id":4,"name":"??????? ????"}],"article_source_types":[{"id":"transported","value":"?????"},{"id":"translated","value":"?????"},{"id":"written","value":"?????"}],"article_statuses":[{"id":"pending","value":"??? ????????"},{"id":"published","value":"?????"},{"id":"rejected","value":"?????"}],"service_types":[{"id":"veterinary_clinic","value":"????? ??????"},{"id":"hotel","value":"?????"},{"id":"shaving","value":"?????"},{"id":"shower","value":"????"},{"id":"walk","value":"???? ?????"},{"id":"training","value":"?????"}]}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SliderAdsImageConversionsMedium {
/*
{
  "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--medium.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  SliderAdsImageConversionsMedium({
    this.url,
  });

  SliderAdsImageConversionsMedium.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class SliderAdsImageConversionsSmall {
/*
{
  "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--small.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  SliderAdsImageConversionsSmall({
    this.url,
  });

  SliderAdsImageConversionsSmall.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class SliderAdsImageConversionsLarge {
/*
{
  "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--large.jpg"
}
*/

  String? url;
  Map<String, dynamic> __origJson = {};

  SliderAdsImageConversionsLarge({
    this.url,
  });

  SliderAdsImageConversionsLarge.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    url = json["url"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class SliderAdsImageConversions {
/*
{
  "large": {
    "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--large.jpg"
  },
  "small": {
    "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--small.jpg"
  },
  "medium": {
    "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--medium.jpg"
  }
}
*/

  SliderAdsImageConversionsLarge? large;
  SliderAdsImageConversionsSmall? small;
  SliderAdsImageConversionsMedium? medium;
  Map<String, dynamic> __origJson = {};

  SliderAdsImageConversions({
    this.large,
    this.small,
    this.medium,
  });

  SliderAdsImageConversions.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    large = (json["large"] != null && (json["large"] is Map))
        ? SliderAdsImageConversionsLarge.fromJson(json["large"])
        : null;
    small = (json["small"] != null && (json["small"] is Map))
        ? SliderAdsImageConversionsSmall.fromJson(json["small"])
        : null;
    medium = (json["medium"] != null && (json["medium"] is Map))
        ? SliderAdsImageConversionsMedium.fromJson(json["medium"])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (large != null) {
      data["large"] = large!.toJson();
    }
    if (small != null) {
      data["small"] = small!.toJson();
    }
    if (medium != null) {
      data["medium"] = medium!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class SliderAdsImage {
/*
{
  "id": 1720,
  "conversions": {
    "large": {
      "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--large.jpg"
    },
    "small": {
      "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--small.jpg"
    },
    "medium": {
      "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--medium.jpg"
    }
  },
  "file_name": "Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=-.jpg",
  "properties": [
    null
  ]
}
*/

  String? id;
  SliderAdsImageConversions? conversions;
  String? fileName;
  List<String?>? properties;
  Map<String, dynamic> __origJson = {};

  SliderAdsImage({
    this.id,
    this.conversions,
    this.fileName,
    this.properties,
  });

  SliderAdsImage.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    conversions = (json["conversions"] != null && (json["conversions"] is Map))
        ? SliderAdsImageConversions.fromJson(json["conversions"])
        : null;
    fileName = json["file_name"]?.toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (conversions != null) {
      data["conversions"] = conversions!.toJson();
    }
    data["file_name"] = fileName;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class SliderAds {
/*
{
  "id": 14,
  "title": "Chjvhh",
  "description": "Chhcghhhuj",
  "target": "product",
  "target_id": 245,
  "target_url": null,
  "image": {
    "id": 1720,
    "conversions": {
      "large": {
        "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--large.jpg"
      },
      "small": {
        "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--small.jpg"
      },
      "medium": {
        "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--medium.jpg"
      }
    },
    "file_name": "Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=-.jpg",
    "properties": [
      null
    ]
  }
}
*/

  String? id;
  String? title;
  String? description;
  String? target;
  String? targetId;
  String? targetUrl;
  SliderAdsImage? image;
  Map<String, dynamic> __origJson = {};

  SliderAds({
    this.id,
    this.title,
    this.description,
    this.target,
    this.targetId,
    this.targetUrl,
    this.image,
  });

  SliderAds.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    title = json["title"]?.toString();
    description = json["description"]?.toString();
    target = json["target"]?.toString();
    targetId = json["target_id"]?.toString();
    targetUrl = json["target_url"]?.toString();
    image = (json["image"] != null && (json["image"] is Map))
        ? SliderAdsImage.fromJson(json["image"])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["title"] = title;
    data["description"] = description;
    data["target"] = target;
    data["target_id"] = targetId;
    data["target_url"] = targetUrl;
    if (image != null) {
      data["image"] = image!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class Slider {
/*
{
  "ads": [
    {
      "id": 14,
      "title": "Chjvhh",
      "description": "Chhcghhhuj",
      "target": "product",
      "target_id": 245,
      "target_url": null,
      "image": {
        "id": 1720,
        "conversions": {
          "large": {
            "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--large.jpg"
          },
          "small": {
            "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--small.jpg"
          },
          "medium": {
            "url": "https://api.thepaws.app/storage/media/1720/conversions/Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=--medium.jpg"
          }
        },
        "file_name": "Nn3QWtnsPDPnWsLrUsJhUxrcIXTB84-metaMjBDQzRFOTEtQkU2OS00Qzc5LUE5QUItOUE4MjUyODBEMjNCLmpwZWc=-.jpg",
        "properties": [
          null
        ]
      }
    }
  ]
}
*/

  List<SliderAds?>? ads;
  Map<String, dynamic> __origJson = {};

  Slider({
    this.ads,
  });

  Slider.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    if (json["ads"] != null && (json["ads"] is List)) {
      final v = json["ads"];
      final arr0 = <SliderAds>[];
      v.forEach((v) {
        arr0.add(SliderAds.fromJson(v));
      });
      ads = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (ads != null) {
      final v = ads;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["ads"] = arr0;
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class BasicResponse {
  final List<LanguagesBean>? languages;
  final List<CurrenciesBean>? currencies;
  final List<GovernoratesBean>? governorates;
  final List<ColorsBean>? colors;
  final About_appBean? aboutApp;
  final EnumsBean? enums;

  final List<SliderAds>? ads;

  BasicResponse(this.languages, this.ads, this.currencies, this.governorates,
      this.colors, this.aboutApp, this.enums);

  static BasicResponse fromMap(Map<String, dynamic> map) {
    BasicResponse basicResponse = BasicResponse(
      map['languages'] != null
          ? ([]..addAll(
              (map['languages'] as List).map((o) => LanguagesBean.fromMap(o))))
          : null,
      map['ads'] != null
          ? ([]..addAll((map['ads'] as List).map((o) => SliderAds.fromJson(o))))
          : null,
      map['currencies'] != null
          ? ([]..addAll((map['currencies'] as List)
              .map((o) => CurrenciesBean.fromMap(o))))
          : null,
      map['governorates'] != null
          ? ([]..addAll((map['governorates'] as List)
              .map((o) => GovernoratesBean.fromMap(o))))
          : null,
      map['colors'] != null
          ? ([]
            ..addAll((map['colors'] as List).map((o) => ColorsBean.fromMap(o))))
          : null,
      map['about_app'] != null ? About_appBean.fromMap(map['about_app']) : null,
      map['enums'] != null ? EnumsBean.fromMap(map['enums']) : null,
    );
    return basicResponse;
  }

  Map toJson() => {
        "ads": ads?.map((o) => o.toJson()).toList(growable: false),
        "languages": languages?.map((o) => o.toJson()).toList(growable: false),
        "currencies":
            currencies?.map((o) => o.toJson()).toList(growable: false),
        "governorates":
            governorates?.map((o) => o.toJson()).toList(growable: false),
        "colors": colors?.map((o) => o.toJson()).toList(growable: false),
        "about_app": aboutApp?.toJson(),
        "enums": enums?.toJson(),
      }..removeWhere((k, v) => v == null);
}

/// account_types : [{"id":"breeder","value":"????"},{"id":"service_provider","value":"???? ????"}]
/// username_types : [{"id":"email","value":"???? ????????"},{"id":"mobile","value":"??? ??????"},{"id":"facebook","value":"??????"},{"id":"google","value":"????"}]
/// enquiry_types : [{"id":"enquiry","value":"???????"},{"id":"request","value":"???"},{"id":"complaint","value":"????"},{"id":"other","value":"????"}]
/// animal_types : [{"id":"dog","value":"???"},{"id":"cat","value":"??"}]
/// article_tags : [{"id":1,"name":"?????"},{"id":2,"name":"?????"},{"id":3,"name":"???????"},{"id":4,"name":"??????? ????"}]
/// article_source_types : [{"id":"transported","value":"?????"},{"id":"translated","value":"?????"},{"id":"written","value":"?????"}]
/// article_statuses : [{"id":"pending","value":"??? ????????"},{"id":"published","value":"?????"},{"id":"rejected","value":"?????"}]
/// service_types : [{"id":"veterinary_clinic","value":"????? ??????"},{"id":"hotel","value":"?????"},{"id":"shaving","value":"?????"},{"id":"shower","value":"????"},{"id":"walk","value":"???? ?????"},{"id":"training","value":"?????"}]

class EnumsBean {
  final List<Account_typesBean>? accountTypes;
  final List<Username_typesBean>? usernameTypes;
  final List<Enquiry_typesBean>? enquiryTypes;
  final List<Animal_typesBean>? animalTypes;
  final List<Article_tagsBean>? articleTags;
  final List<Article_source_typesBean>? articleSourceTypes;
  final List<Article_statusesBean>? articleStatuses;
  final List<Service_typesBean>? serviceTypes;

  EnumsBean(
      this.accountTypes,
      this.usernameTypes,
      this.enquiryTypes,
      this.animalTypes,
      this.articleTags,
      this.articleSourceTypes,
      this.articleStatuses,
      this.serviceTypes);

  static EnumsBean fromMap(Map<String, dynamic> map) {
    EnumsBean enumsBean = EnumsBean(
      map['account_types'] != null
          ? ([]..addAll((map['account_types'] as List)
              .map((o) => Account_typesBean.fromMap(o))))
          : null,
      map['username_types'] != null
          ? ([]..addAll((map['username_types'] as List)
              .map((o) => Username_typesBean.fromMap(o))))
          : null,
      map['enquiry_types'] != null
          ? ([]..addAll((map['enquiry_types'] as List)
              .map((o) => Enquiry_typesBean.fromMap(o))))
          : null,
      map['animal_types'] != null
          ? ([]..addAll((map['animal_types'] as List)
              .map((o) => Animal_typesBean.fromMap(o))))
          : null,
      map['article_tags'] != null
          ? ([]..addAll((map['article_tags'] as List)
              .map((o) => Article_tagsBean.fromMap(o))))
          : null,
      map['article_source_types'] != null
          ? ([]..addAll((map['article_source_types'] as List)
              .map((o) => Article_source_typesBean.fromMap(o))))
          : null,
      map['article_statuses'] != null
          ? ([]..addAll((map['article_statuses'] as List)
              .map((o) => Article_statusesBean.fromMap(o))))
          : null,
      map['service_types'] != null
          ? ([]..addAll((map['service_types'] as List)
              .map((o) => Service_typesBean.fromMap(o))))
          : null,
    );
    return enumsBean;
  }

  Map toJson() => {
        "account_types":
            accountTypes?.map((o) => o.toJson()).toList(growable: false),
        "username_types":
            usernameTypes?.map((o) => o.toJson()).toList(growable: false),
        "enquiry_types":
            enquiryTypes?.map((o) => o.toJson()).toList(growable: false),
        "animal_types":
            animalTypes?.map((o) => o.toJson()).toList(growable: false),
        "article_tags":
            articleTags?.map((o) => o.toJson()).toList(growable: false),
        "article_source_types":
            articleSourceTypes?.map((o) => o.toJson()).toList(growable: false),
        "article_statuses":
            articleStatuses?.map((o) => o.toJson()).toList(growable: false),
        "service_types":
            serviceTypes?.map((o) => o.toJson()).toList(growable: false),
      }..removeWhere((k, v) => v == null);
}

/// id : "veterinary_clinic"
/// value : "????? ??????"

class Service_typesBean {
  final String? id;
  final String? value;

  Service_typesBean(this.id, this.value);

  static Service_typesBean fromMap(Map<String, dynamic> map) {
    Service_typesBean service_typesBean = Service_typesBean(
      map['id'],
      map['value'],
    );
    return service_typesBean;
  }

  Map toJson() => {
        "id": id,
        "value": value,
      }..removeWhere((k, v) => v == null);
}

/// id : "pending"
/// value : "??? ????????"

class Article_statusesBean {
  final String? id;
  final String? value;

  Article_statusesBean(this.id, this.value);

  static Article_statusesBean fromMap(Map<String, dynamic> map) {
    Article_statusesBean article_statusesBean = Article_statusesBean(
      map['id'],
      map['value'],
    );
    return article_statusesBean;
  }

  Map toJson() => {
        "id": id,
        "value": value,
      }..removeWhere((k, v) => v == null);
}

/// id : "transported"
/// value : "?????"

class Article_source_typesBean {
  final String? id;
  final String? value;

  Article_source_typesBean(this.id, this.value);

  static Article_source_typesBean fromMap(Map<String, dynamic> map) {
    Article_source_typesBean article_source_typesBean =
        Article_source_typesBean(
      map['id'],
      map['value'],
    );
    return article_source_typesBean;
  }

  Map toJson() => {
        "id": id,
        "value": value,
      }..removeWhere((k, v) => v == null);
}

/// id : 1
/// name : "?????"

class Article_tagsBean {
  final int? id;
  final String? name;

  Article_tagsBean(this.id, this.name);

  static Article_tagsBean fromMap(Map<String, dynamic> map) {
    Article_tagsBean article_tagsBean = Article_tagsBean(
      map['id'],
      map['name'],
    );
    return article_tagsBean;
  }

  Map toJson() => {
        "id": id,
        "name": name,
      }..removeWhere((k, v) => v == null);
}

/// id : "dog"
/// value : "???"

class Animal_typesBean {
  final String? id;
  final String? value;

  Animal_typesBean(this.id, this.value);

  static Animal_typesBean fromMap(Map<String, dynamic> map) {
    Animal_typesBean animal_typesBean = Animal_typesBean(
      map['id'],
      map['value'],
    );
    return animal_typesBean;
  }

  Map toJson() => {
        "id": id,
        "value": value,
      }..removeWhere((k, v) => v == null);
}

/// id : "enquiry"
/// value : "???????"

class Enquiry_typesBean {
  final String? id;
  final String? value;

  Enquiry_typesBean(this.id, this.value);

  static Enquiry_typesBean fromMap(Map<String, dynamic> map) {
    Enquiry_typesBean enquiry_typesBean = Enquiry_typesBean(
      map['id'],
      map['value'],
    );
    return enquiry_typesBean;
  }

  Map toJson() => {
        "id": id,
        "value": value,
      }..removeWhere((k, v) => v == null);
}

/// id : "email"
/// value : "???? ????????"

class Username_typesBean {
  final String? id;
  final String? value;

  Username_typesBean(this.id, this.value);

  static Username_typesBean fromMap(Map<String, dynamic> map) {
    Username_typesBean username_typesBean = Username_typesBean(
      map['id'],
      map['value'],
    );
    return username_typesBean;
  }

  Map toJson() => {
        "id": id,
        "value": value,
      }..removeWhere((k, v) => v == null);
}

/// id : "breeder"
/// value : "????"

class Account_typesBean {
  final String? id;
  final String? value;

  Account_typesBean(this.id, this.value);

  static Account_typesBean fromMap(Map<String, dynamic> map) {
    Account_typesBean account_typesBean = Account_typesBean(
      map['id'],
      map['value'],
    );
    return account_typesBean;
  }

  Map toJson() => {
        "id": id,
        "value": value,
      }..removeWhere((k, v) => v == null);
}

/// about_us : " "
/// info : {"info_email":"info@paws.com","info_mobile":"9647901911601","info_whats":"9647901911601"}
/// social_networks : {"socials_facebook":"https://facebook.com","socials_twitter":"https://twitter.com","socials_instagram":"https://instagram.com"}

class About_appBean {
  final String? aboutUs;
  final InfoBean? info;
  final Social_networksBean? socialNetworks;

  About_appBean(this.aboutUs, this.info, this.socialNetworks);

  static About_appBean fromMap(Map<String, dynamic> map) {
    About_appBean about_appBean = About_appBean(
      map['about_us'],
      map['info'] != null ? InfoBean.fromMap(map['info']) : null,
      map['social_networks'] != null
          ? Social_networksBean.fromMap(map['social_networks'])
          : null,
    );
    return about_appBean;
  }

  Map toJson() => {
        "about_us": aboutUs,
        "info": info?.toJson(),
        "social_networks": socialNetworks?.toJson(),
      }..removeWhere((k, v) => v == null);
}

/// socials_facebook : "https://facebook.com"
/// socials_twitter : "https://twitter.com"
/// socials_instagram : "https://instagram.com"

class Social_networksBean {
  final String? socialsFacebook;
  final String? socialsTwitter;
  final String? socialsInstagram;

  Social_networksBean(
      this.socialsFacebook, this.socialsTwitter, this.socialsInstagram);

  static Social_networksBean fromMap(Map<String, dynamic> map) {
    Social_networksBean social_networksBean = Social_networksBean(
      map['socials_facebook'],
      map['socials_twitter'],
      map['socials_instagram'],
    );
    return social_networksBean;
  }

  Map toJson() => {
        "socials_facebook": socialsFacebook,
        "socials_twitter": socialsTwitter,
        "socials_instagram": socialsInstagram,
      }..removeWhere((k, v) => v == null);
}

/// info_email : "info@paws.com"
/// info_mobile : "9647901911601"
/// info_whats : "9647901911601"

class InfoBean {
  final String? infoEmail;
  final String? infoMobile;
  final String? infoWhats;

  InfoBean(this.infoEmail, this.infoMobile, this.infoWhats);

  static InfoBean fromMap(Map<String, dynamic> map) {
    InfoBean infoBean = InfoBean(
      map['info_email'],
      map['info_mobile'],
      map['info_whats'],
    );
    return infoBean;
  }

  Map toJson() => {
        "info_email": infoEmail,
        "info_mobile": infoMobile,
        "info_whats": infoWhats,
      }..removeWhere((k, v) => v == null);
}

/// id : 1
/// name : "????"

class ColorsBean {
  final int? id;
  final String? name;

  ColorsBean(this.id, this.name);

  static ColorsBean fromMap(Map<String, dynamic> map) {
    ColorsBean colorsBean = ColorsBean(
      map['id'],
      map['name'],
    );
    return colorsBean;
  }

  Map toJson() => {
        "id": id,
        "name": name,
      }..removeWhere((k, v) => v == null);
}

/// id : 1
/// name : "?????"

class GovernoratesBean {
  final int? id;
  final String? name;

  GovernoratesBean(this.id, this.name);

  static GovernoratesBean fromMap(Map<String, dynamic> map) {
    GovernoratesBean governoratesBean = GovernoratesBean(
      map['id'],
      map['name'],
    );
    return governoratesBean;
  }

  Map toJson() => {
        "id": id,
        "name": name,
      }..removeWhere((k, v) => v == null);
}

/// id : "USD"
/// name : {"ar":"??????? ????????","en":"United States dollar","ku":"??????? ????????"}
/// parts : 100
/// symbol : "$"

class CurrenciesBean {
  final String? id;
  final NameBean? name;
  final int? parts;
  final String? symbol;

  CurrenciesBean(this.id, this.name, this.parts, this.symbol);

  static CurrenciesBean fromMap(Map<String, dynamic> map) {
    CurrenciesBean currenciesBean = CurrenciesBean(
      map['id'],
      map['name'] != null ? NameBean.fromMap(map['name']) : null,
      map['parts'],
      map['symbol'],
    );
    return currenciesBean;
  }

  Map toJson() => {
        "id": id,
        "name": name?.toJson(),
        "parts": parts,
        "symbol": symbol,
      }..removeWhere((k, v) => v == null);
}

/// ar : "??????? ????????"
/// en : "United States dollar"
/// ku : "??????? ????????"

class NameBean {
  final String? ar;
  final String? en;
  final String? ku;

  NameBean(this.ar, this.en, this.ku);

  static NameBean fromMap(Map<String, dynamic> map) {
    NameBean nameBean = NameBean(
      map['ar'],
      map['en'],
      map['ku'],
    );
    return nameBean;
  }

  Map toJson() => {
        "ar": ar,
        "en": en,
        "ku": ku,
      }..removeWhere((k, v) => v == null);
}

/// id : "en"
/// name : "English"
/// native : "English"
/// direction : "ltr"

class LanguagesBean {
  final String? id;
  final String? name;
  final String? native;
  final String? direction;

  LanguagesBean(this.id, this.name, this.native, this.direction);

  static LanguagesBean fromMap(Map<String, dynamic> map) {
    LanguagesBean languagesBean = LanguagesBean(
      map['id'],
      map['name'],
      map['native'],
      map['direction'],
    );
    return languagesBean;
  }

  Map toJson() => {
        "id": id,
        "name": name,
        "native": native,
        "direction": direction,
      }..removeWhere((k, v) => v == null);
}
