import 'ArticleDetails.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CartDataDataTotalAmountIqd {
/*
{
  "value": "5944680.000",
  "currency": "د.ع",
  "formatted": "5,944,680 د.ع"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  CartDataDataTotalAmountIqd({
    this.value,
    this.currency,
    this.formatted,
  });
  CartDataDataTotalAmountIqd.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CartDataDataTotalAmount {
/*
{
  "value": "5944680.000",
  "currency": "د.ع",
  "formatted": "5,944,680 د.ع"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  CartDataDataTotalAmount({
    this.value,
    this.currency,
    this.formatted,
  });
  CartDataDataTotalAmount.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CartDataDataPromocodeDiscountAmount {
/*
{
  "value": "0.000",
  "currency": "د.ع",
  "formatted": "0 د.ع"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  CartDataDataPromocodeDiscountAmount({
    this.value,
    this.currency,
    this.formatted,
  });
  CartDataDataPromocodeDiscountAmount.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CartDataDataShippingCosts {
/*
{
  "value": "0.000",
  "currency": "د.ع",
  "formatted": "0 د.ع"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  CartDataDataShippingCosts({
    this.value,
    this.currency,
    this.formatted,
  });
  CartDataDataShippingCosts.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CartDataDataProductsPrice {
/*
{
  "value": "5944680.000",
  "currency": "د.ع",
  "formatted": "5,944,680 د.ع"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  CartDataDataProductsPrice({
    this.value,
    this.currency,
    this.formatted,
  });
  CartDataDataProductsPrice.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CartDataDataItemsTotalPrice {
/*
{
  "value": "5944680.000",
  "currency": "د.ع",
  "formatted": "5,944,680 د.ع"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  CartDataDataItemsTotalPrice({
    this.value,
    this.currency,
    this.formatted,
  });
  CartDataDataItemsTotalPrice.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CartDataDataItemsUnitPriceOriginal {
/*
{
  "value": "1981560.000",
  "currency": "د.ع",
  "formatted": "1,981,560 د.ع"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  CartDataDataItemsUnitPriceOriginal({
    this.value,
    this.currency,
    this.formatted,
  });
  CartDataDataItemsUnitPriceOriginal.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CartDataDataItemsUnitPrice {
/*
{
  "value": "1981560.000",
  "currency": "د.ع",
  "formatted": "1,981,560 د.ع"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  CartDataDataItemsUnitPrice({
    this.value,
    this.currency,
    this.formatted,
  });
  CartDataDataItemsUnitPrice.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CartDataDataItems {
/*
{
  "id": 1,
  "product_id": 1,
  "title": "Doloribus officiis vel dicta culpa rerum fugit sunt. (عنصر)",
  "request_min": 3,
  "unit_price": {
    "value": "1981560.000",
    "currency": "د.ع",
    "formatted": "1,981,560 د.ع"
  },
  "unit_price_original": {
    "value": "1981560.000",
    "currency": "د.ع",
    "formatted": "1,981,560 د.ع"
  },
  "total_price": {
    "value": "5944680.000",
    "currency": "د.ع",
    "formatted": "5,944,680 د.ع"
  },
  "total_quantity": 3,
  "is_deleted": false,
  "is_quantity_available": true
}
*/
  ImageBean? image;

  String? id;
  String? productId;
  String? title;
  String? requestMin;
  CartDataDataItemsUnitPrice? unitPrice;
  CartDataDataItemsUnitPriceOriginal? unitPriceOriginal;
  CartDataDataItemsTotalPrice? totalPrice;
  String? totalQuantity;
  bool? isDeleted;
  bool? isQuantityAvailable;
  Map<String, dynamic> __origJson = {};

  CartDataDataItems({
    this.id,
    this.productId,
    this.title,
    this.requestMin,
    this.unitPrice,
    this.unitPriceOriginal,
    this.totalPrice,
    this.totalQuantity,
    this.isDeleted,
    this.isQuantityAvailable,
  });
  CartDataDataItems.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    productId = json["product_id"]?.toString();
    title = json["title"]?.toString();
    image = json['image'] != null ? ImageBean.fromMap(json['image']) : null;

    requestMin = json["request_min"]?.toString();
    unitPrice = (json["unit_price"] != null && (json["unit_price"] is Map))
        ? CartDataDataItemsUnitPrice.fromJson(json["unit_price"])
        : null;
    unitPriceOriginal = (json["unit_price_original"] != null &&
            (json["unit_price_original"] is Map))
        ? CartDataDataItemsUnitPriceOriginal.fromJson(
            json["unit_price_original"])
        : null;
    totalPrice = (json["total_price"] != null && (json["total_price"] is Map))
        ? CartDataDataItemsTotalPrice.fromJson(json["total_price"])
        : null;
    totalQuantity = json["total_quantity"]?.toString();
    isDeleted = json["is_deleted"];
    isQuantityAvailable = json["is_quantity_available"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["product_id"] = productId;
    data["title"] = title;
    data["request_min"] = requestMin;
    if (unitPrice != null) {
      data["unit_price"] = unitPrice!.toJson();
    }
    if (image != null) {
      data["image"] = image!.toJson();
    }
    if (unitPriceOriginal != null) {
      data["unit_price_original"] = unitPriceOriginal!.toJson();
    }
    if (totalPrice != null) {
      data["total_price"] = totalPrice!.toJson();
    }
    data["total_quantity"] = totalQuantity;
    data["is_deleted"] = isDeleted;
    data["is_quantity_available"] = isQuantityAvailable;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CartDataDataState {
/*
{
  "id": "initiated",
  "desc": "قيد الإنشاء"
}
*/

  String? id;
  String? desc;
  Map<String, dynamic> __origJson = {};

  CartDataDataState({
    this.id,
    this.desc,
  });
  CartDataDataState.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    desc = json["desc"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["desc"] = desc;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CartDataData {
/*
{
  "id": 1,
  "state": {
    "id": "initiated",
    "desc": "قيد الإنشاء"
  },
  "requested_at": null,
  "items": [
    {
      "id": 1,
      "product_id": 1,
      "title": "Doloribus officiis vel dicta culpa rerum fugit sunt. (عنصر)",
      "request_min": 3,
      "unit_price": {
        "value": "1981560.000",
        "currency": "د.ع",
        "formatted": "1,981,560 د.ع"
      },
      "unit_price_original": {
        "value": "1981560.000",
        "currency": "د.ع",
        "formatted": "1,981,560 د.ع"
      },
      "total_price": {
        "value": "5944680.000",
        "currency": "د.ع",
        "formatted": "5,944,680 د.ع"
      },
      "total_quantity": 3,
      "is_deleted": false,
      "is_quantity_available": true
    }
  ],
  "products_price": {
    "value": "5944680.000",
    "currency": "د.ع",
    "formatted": "5,944,680 د.ع"
  },
  "shipping_costs": {
    "value": "0.000",
    "currency": "د.ع",
    "formatted": "0 د.ع"
  },
  "promocode_discount_amount": {
    "value": "0.000",
    "currency": "د.ع",
    "formatted": "0 د.ع"
  },
  "total_amount": {
    "value": "5944680.000",
    "currency": "د.ع",
    "formatted": "5,944,680 د.ع"
  },
  "usd_iqd_conversion_rate": 1470,
  "total_amount_iqd": {
    "value": "5944680.000",
    "currency": "د.ع",
    "formatted": "5,944,680 د.ع"
  },
  "shipping_address": null,
  "promocode": null
}
*/

  String? id;
  CartDataDataState? state;
  String? requestedAt;
  List<CartDataDataItems>? items;
  CartDataDataProductsPrice? productsPrice;
  CartDataDataShippingCosts? shippingCosts;
  CartDataDataPromocodeDiscountAmount? promocodeDiscountAmount;
  CartDataDataTotalAmount? totalAmount;
  String? usdIqdConversionRate;
  CartDataDataTotalAmountIqd? totalAmountIqd;
  dynamic shippingAddress;
  dynamic promocode;
  Map<String, dynamic> __origJson = {};

  CartDataData({
    this.id,
    this.state,
    this.requestedAt,
    this.items,
    this.productsPrice,
    this.shippingCosts,
    this.promocodeDiscountAmount,
    this.totalAmount,
    this.usdIqdConversionRate,
    this.totalAmountIqd,
    this.shippingAddress,
    this.promocode,
  });
  CartDataData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    state = (json["state"] != null && (json["state"] is Map))
        ? CartDataDataState.fromJson(json["state"])
        : null;
    requestedAt = json["requested_at"]?.toString();
    if (json["items"] != null && (json["items"] is List)) {
      final v = json["items"];
      final arr0 = <CartDataDataItems>[];
      v.forEach((v) {
        arr0.add(CartDataDataItems.fromJson(v));
      });
      items = arr0;
    }
    productsPrice =
        (json["products_price"] != null && (json["products_price"] is Map))
            ? CartDataDataProductsPrice.fromJson(json["products_price"])
            : null;
    shippingCosts =
        (json["shipping_costs"] != null && (json["shipping_costs"] is Map))
            ? CartDataDataShippingCosts.fromJson(json["shipping_costs"])
            : null;
    promocodeDiscountAmount = (json["promocode_discount_amount"] != null &&
            (json["promocode_discount_amount"] is Map))
        ? CartDataDataPromocodeDiscountAmount.fromJson(
            json["promocode_discount_amount"])
        : null;
    totalAmount =
        (json["total_amount"] != null && (json["total_amount"] is Map))
            ? CartDataDataTotalAmount.fromJson(json["total_amount"])
            : null;
    usdIqdConversionRate = json["usd_iqd_conversion_rate"]?.toString();
    totalAmountIqd =
        (json["total_amount_iqd"] != null && (json["total_amount_iqd"] is Map))
            ? CartDataDataTotalAmountIqd.fromJson(json["total_amount_iqd"])
            : null;
    try {
      shippingAddress = json["shipping_address"];
    } catch (e) {}
    promocode = json["promocode"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (state != null) {
      data["state"] = state!.toJson();
    }
    data["requested_at"] = requestedAt;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data["items"] = arr0;
    }
    if (productsPrice != null) {
      data["products_price"] = productsPrice!.toJson();
    }
    if (shippingCosts != null) {
      data["shipping_costs"] = shippingCosts!.toJson();
    }
    if (promocodeDiscountAmount != null) {
      data["promocode_discount_amount"] = promocodeDiscountAmount!.toJson();
    }
    if (totalAmount != null) {
      data["total_amount"] = totalAmount!.toJson();
    }
    data["usd_iqd_conversion_rate"] = usdIqdConversionRate;
    if (totalAmountIqd != null) {
      data["total_amount_iqd"] = totalAmountIqd!.toJson();
    }
    data["shipping_address"] = shippingAddress;
    data["promocode"] = promocode;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class CartData {
/*
{
  "data": {
    "id": 1,
    "state": {
      "id": "initiated",
      "desc": "قيد الإنشاء"
    },
    "requested_at": null,
    "items": [
      {
        "id": 1,
        "product_id": 1,
        "title": "Doloribus officiis vel dicta culpa rerum fugit sunt. (عنصر)",
        "request_min": 3,
        "unit_price": {
          "value": "1981560.000",
          "currency": "د.ع",
          "formatted": "1,981,560 د.ع"
        },
        "unit_price_original": {
          "value": "1981560.000",
          "currency": "د.ع",
          "formatted": "1,981,560 د.ع"
        },
        "total_price": {
          "value": "5944680.000",
          "currency": "د.ع",
          "formatted": "5,944,680 د.ع"
        },
        "total_quantity": 3,
        "is_deleted": false,
        "is_quantity_available": true
      }
    ],
    "products_price": {
      "value": "5944680.000",
      "currency": "د.ع",
      "formatted": "5,944,680 د.ع"
    },
    "shipping_costs": {
      "value": "0.000",
      "currency": "د.ع",
      "formatted": "0 د.ع"
    },
    "promocode_discount_amount": {
      "value": "0.000",
      "currency": "د.ع",
      "formatted": "0 د.ع"
    },
    "total_amount": {
      "value": "5944680.000",
      "currency": "د.ع",
      "formatted": "5,944,680 د.ع"
    },
    "usd_iqd_conversion_rate": 1470,
    "total_amount_iqd": {
      "value": "5944680.000",
      "currency": "د.ع",
      "formatted": "5,944,680 د.ع"
    },
    "shipping_address": null,
    "promocode": null
  }
}
*/

  CartDataData? data;
  Map<String, dynamic> __origJson = {};

  CartData({
    this.data,
  });
  CartData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    data = (json["data"] != null && (json["data"] is Map))
        ? CartDataData.fromJson(json["data"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
