///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NotificationsResponseMeta {
/*
{
  "current_page": 1,
  "from": 1,
  "path": "http://paws.test/api/v1/notifications",
  "per_page": 1,
  "to": 1
}
*/

  String? currentPage;
  String? from;
  String? path;
  String? perPage;
  String? to;
  Map<String, dynamic> __origJson = {};

  NotificationsResponseMeta({
    this.currentPage,
    this.from,
    this.path,
    this.perPage,
    this.to,
  });
  NotificationsResponseMeta.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    currentPage = json["current_page"]?.toString();
    from = json["from"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toString();
    to = json["to"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = currentPage;
    data["from"] = from;
    data["path"] = path;
    data["per_page"] = perPage;
    data["to"] = to;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class NotificationsResponseLinks {
/*
{
  "first": "http://paws.test/api/v1/notifications?perpage=1&category=general&page=1",
  "last": null,
  "prev": null,
  "next": "http://paws.test/api/v1/notifications?perpage=1&category=general&page=2"
}
*/

  String? first;
  String? last;
  String? prev;
  String? next;
  Map<String, dynamic> __origJson = {};

  NotificationsResponseLinks({
    this.first,
    this.last,
    this.prev,
    this.next,
  });
  NotificationsResponseLinks.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    first = json["first"]?.toString();
    last = json["last"]?.toString();
    prev = json["prev"]?.toString();
    next = json["next"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["first"] = first;
    data["last"] = last;
    data["prev"] = prev;
    data["next"] = next;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class NotificationsResponseDataCreatedAt {
/*
{
  "value": "2021-12-16 23:59:54",
  "human": "23:59 pm"
}
*/

  String? value;
  String? human;
  Map<String, dynamic> __origJson = {};

  NotificationsResponseDataCreatedAt({
    this.value,
    this.human,
  });
  NotificationsResponseDataCreatedAt.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    human = json["human"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["human"] = human;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class NotificationsResponseDataData {
  Map<String, dynamic> __origJson = {};

  NotificationsResponseDataData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class NotificationsResponseData {
/*
{
  "id": "4b122d3e-fedd-4d05-8c39-487df196f772",
  "key": "General",
  "category": "Circulate",
  "text": "I'm quite tired of being upset, and their curls got entangled together. Alice was a paper label, with the bread-and-butter getting so thin--and the twinkling of the March Hare had just succeeded in.",
  "data": {},
  "created_at": {
    "value": "2021-12-16 23:59:54",
    "human": "23:59 pm"
  },
  "is_seen": true
}
*/

  String? id;
  String? key;
  String? category;
  String? text;
  NotificationsResponseDataData? data;
  NotificationsResponseDataCreatedAt? createdAt;
  bool? isSeen;
  Map<String, dynamic> __origJson = {};

  NotificationsResponseData({
    this.id,
    this.key,
    this.category,
    this.text,
    this.data,
    this.createdAt,
    this.isSeen,
  });
  NotificationsResponseData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    key = json["key"]?.toString();
    category = json["category"]?.toString();
    text = json["text"]?.toString();
    data = (json["data"] != null && (json["data"] is Map))
        ? NotificationsResponseDataData.fromJson(json["data"])
        : null;
    createdAt = (json["created_at"] != null && (json["created_at"] is Map))
        ? NotificationsResponseDataCreatedAt.fromJson(json["created_at"])
        : null;
    isSeen = json["is_seen"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["key"] = key;
    data["category"] = category;
    data["text"] = text;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    if (createdAt != null) {
      data["created_at"] = createdAt!.toJson();
    }
    data["is_seen"] = isSeen;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class NotificationsResponse {
/*
{
  "data": [
    {
      "id": "4b122d3e-fedd-4d05-8c39-487df196f772",
      "key": "General",
      "category": "Circulate",
      "text": "I'm quite tired of being upset, and their curls got entangled together. Alice was a paper label, with the bread-and-butter getting so thin--and the twinkling of the March Hare had just succeeded in.",
      "data": {},
      "created_at": {
        "value": "2021-12-16 23:59:54",
        "human": "23:59 pm"
      },
      "is_seen": true
    }
  ],
  "links": {
    "first": "http://paws.test/api/v1/notifications?perpage=1&category=general&page=1",
    "last": null,
    "prev": null,
    "next": "http://paws.test/api/v1/notifications?perpage=1&category=general&page=2"
  },
  "meta": {
    "current_page": 1,
    "from": 1,
    "path": "http://paws.test/api/v1/notifications",
    "per_page": 1,
    "to": 1
  }
}
*/

  List<NotificationsResponseData>? data;
  NotificationsResponseLinks? links;
  NotificationsResponseMeta? meta;
  Map<String, dynamic> __origJson = {};

  NotificationsResponse({
    this.data,
    this.links,
    this.meta,
  });
  NotificationsResponse.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    if (json["data"] != null && (json["data"] is List)) {
      final v = json["data"];
      final arr0 = <NotificationsResponseData>[];
      v.forEach((v) {
        arr0.add(NotificationsResponseData.fromJson(v));
      });
      this.data = arr0;
    }
    links = (json["links"] != null && (json["links"] is Map))
        ? NotificationsResponseLinks.fromJson(json["links"])
        : null;
    meta = (json["meta"] != null && (json["meta"] is Map))
        ? NotificationsResponseMeta.fromJson(json["meta"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data["data"] = arr0;
    }
    if (links != null) {
      data["links"] = links!.toJson();
    }
    if (meta != null) {
      data["meta"] = meta!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
