import 'ArticleDetails.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderDetailsResponseDataPromocodeStatus {
/*
{
  "id": "active",
  "desc": "Active"
}
*/

  String? id;
  String? desc;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataPromocodeStatus({
    this.id,
    this.desc,
  });
  OrderDetailsResponseDataPromocodeStatus.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    desc = json["desc"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["desc"] = desc;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataPromocode {
/*
{
  "id": 1,
  "status": {
    "id": "active",
    "desc": "Active"
  },
  "code": "EJR5-GPDC",
  "reward": "30 %"
}
*/

  String? id;
  OrderDetailsResponseDataPromocodeStatus? status;
  String? code;
  String? reward;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataPromocode({
    this.id,
    this.status,
    this.code,
    this.reward,
  });
  OrderDetailsResponseDataPromocode.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    status = (json["status"] != null && (json["status"] is Map))
        ? OrderDetailsResponseDataPromocodeStatus.fromJson(json["status"])
        : null;
    code = json["code"]?.toString();
    reward = json["reward"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (status != null) {
      data["status"] = status!.toJson();
    }
    data["code"] = code;
    data["reward"] = reward;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataShippingAddressGovernorate {
/*
{
  "id": 1,
  "name": "Baghdad"
}
*/

  String? id;
  String? name;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataShippingAddressGovernorate({
    this.id,
    this.name,
  });
  OrderDetailsResponseDataShippingAddressGovernorate.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    name = json["name"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataShippingAddress {
/*
{
  "id": 24,
  "coordinates": null,
  "governorate": {
    "id": 1,
    "name": "Baghdad"
  },
  "region_desc": "karah",
  "address": "karah",
  "landmarks": "",
  "building_number": null,
  "mobile": "9647901911601"
}
*/

  String? id;
  String? coordinates;
  OrderDetailsResponseDataShippingAddressGovernorate? governorate;
  String? regionDesc;
  String? address;
  String? landmarks;
  String? buildingNumber;
  String? mobile;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataShippingAddress({
    this.id,
    this.coordinates,
    this.governorate,
    this.regionDesc,
    this.address,
    this.landmarks,
    this.buildingNumber,
    this.mobile,
  });
  OrderDetailsResponseDataShippingAddress.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    coordinates = json["coordinates"]?.toString();
    governorate = (json["governorate"] != null && (json["governorate"] is Map))
        ? OrderDetailsResponseDataShippingAddressGovernorate.fromJson(
            json["governorate"])
        : null;
    regionDesc = json["region_desc"]?.toString();
    address = json["address"]?.toString();
    landmarks = json["landmarks"]?.toString();
    buildingNumber = json["building_number"]?.toString();
    mobile = json["mobile"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["coordinates"] = coordinates;
    if (governorate != null) {
      data["governorate"] = governorate!.toJson();
    }
    data["region_desc"] = regionDesc;
    data["address"] = address;
    data["landmarks"] = landmarks;
    data["building_number"] = buildingNumber;
    data["mobile"] = mobile;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataTotalAmountIqd {
/*
{
  "value": "782499.200",
  "currency": "IQD",
  "formatted": "782,499 IQD"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataTotalAmountIqd({
    this.value,
    this.currency,
    this.formatted,
  });
  OrderDetailsResponseDataTotalAmountIqd.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataTotalAmount {
/*
{
  "value": "782499.200",
  "currency": "IQD",
  "formatted": "782,499 IQD"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataTotalAmount({
    this.value,
    this.currency,
    this.formatted,
  });
  OrderDetailsResponseDataTotalAmount.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataPromocodeDiscountAmount {
/*
{
  "value": "826.800",
  "currency": "IQD",
  "formatted": "827 IQD"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataPromocodeDiscountAmount({
    this.value,
    this.currency,
    this.formatted,
  });
  OrderDetailsResponseDataPromocodeDiscountAmount.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataShippingCosts {
/*
{
  "value": "780570.000",
  "currency": "IQD",
  "formatted": "780,570 IQD"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataShippingCosts({
    this.value,
    this.currency,
    this.formatted,
  });
  OrderDetailsResponseDataShippingCosts.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataProductsPrice {
/*
{
  "value": "2756.000",
  "currency": "IQD",
  "formatted": "2,756 IQD"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataProductsPrice({
    this.value,
    this.currency,
    this.formatted,
  });
  OrderDetailsResponseDataProductsPrice.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataItemsTotalPrice {
/*
{
  "value": "2756.000",
  "currency": "IQD",
  "formatted": "2,756 IQD"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataItemsTotalPrice({
    this.value,
    this.currency,
    this.formatted,
  });
  OrderDetailsResponseDataItemsTotalPrice.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataItemsUnitPriceOriginal {
/*
{
  "value": "689.000",
  "currency": "IQD",
  "formatted": "689 IQD"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataItemsUnitPriceOriginal({
    this.value,
    this.currency,
    this.formatted,
  });
  OrderDetailsResponseDataItemsUnitPriceOriginal.fromJson(
      Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataItemsUnitPrice {
/*
{
  "value": "689.000",
  "currency": "IQD",
  "formatted": "689 IQD"
}
*/

  String? value;
  String? currency;
  String? formatted;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataItemsUnitPrice({
    this.value,
    this.currency,
    this.formatted,
  });
  OrderDetailsResponseDataItemsUnitPrice.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    value = json["value"]?.toString();
    currency = json["currency"]?.toString();
    formatted = json["formatted"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["value"] = value;
    data["currency"] = currency;
    data["formatted"] = formatted;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataItems {
/*
{
  "id": 1,
  "product_id": 1,
  "title": "Blanditiis minima explicabo incidunt ratione mollitia aut aut repellat consequuntur repellendus qui totam voluptatem. (Item)",
  "request_min": 1,
  "unit_price": {
    "value": "689.000",
    "currency": "IQD",
    "formatted": "689 IQD"
  },
  "unit_price_original": {
    "value": "689.000",
    "currency": "IQD",
    "formatted": "689 IQD"
  },
  "total_price": {
    "value": "2756.000",
    "currency": "IQD",
    "formatted": "2,756 IQD"
  },
  "total_quantity": 4,
  "is_deleted": false,
  "is_quantity_available": true
}
*/
  ImageBean? image;

  String? id;
  String? productId;
  String? title;
  String? requestMin;
  OrderDetailsResponseDataItemsUnitPrice? unitPrice;
  OrderDetailsResponseDataItemsUnitPriceOriginal? unitPriceOriginal;
  OrderDetailsResponseDataItemsTotalPrice? totalPrice;
  String? totalQuantity;
  bool? isDeleted;
  bool? isQuantityAvailable;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataItems({
    this.id,
    this.productId,
    this.title,
    this.requestMin,
    this.unitPrice,
    this.unitPriceOriginal,
    this.totalPrice,
    this.totalQuantity,
    this.isDeleted,
    this.isQuantityAvailable,
  });
  OrderDetailsResponseDataItems.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    productId = json["product_id"]?.toString();
    title = json["title"]?.toString();
    image = json['image'] != null ? ImageBean.fromMap(json['image']) : null;
    requestMin = json["request_min"]?.toString();
    unitPrice = (json["unit_price"] != null && (json["unit_price"] is Map))
        ? OrderDetailsResponseDataItemsUnitPrice.fromJson(json["unit_price"])
        : null;
    unitPriceOriginal = (json["unit_price_original"] != null &&
            (json["unit_price_original"] is Map))
        ? OrderDetailsResponseDataItemsUnitPriceOriginal.fromJson(
            json["unit_price_original"])
        : null;
    totalPrice = (json["total_price"] != null && (json["total_price"] is Map))
        ? OrderDetailsResponseDataItemsTotalPrice.fromJson(json["total_price"])
        : null;
    totalQuantity = json["total_quantity"]?.toString();
    isDeleted = json["is_deleted"];
    isQuantityAvailable = json["is_quantity_available"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["product_id"] = productId;
    data["title"] = title;
    data["request_min"] = requestMin;
    if (unitPrice != null) {
      data["unit_price"] = unitPrice!.toJson();
    }
    if (image != null) {
      data["image"] = image!.toJson();
    }
    if (unitPriceOriginal != null) {
      data["unit_price_original"] = unitPriceOriginal!.toJson();
    }
    if (totalPrice != null) {
      data["total_price"] = totalPrice!.toJson();
    }
    data["total_quantity"] = totalQuantity;
    data["is_deleted"] = isDeleted;
    data["is_quantity_available"] = isQuantityAvailable;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseDataState {
/*
{
  "id": "cancelled",
  "desc": "Cancelled"
}
*/

  String? id;
  String? desc;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseDataState({
    this.id,
    this.desc,
  });
  OrderDetailsResponseDataState.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    desc = json["desc"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["desc"] = desc;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponseData {
/*
{
  "id": 1,
  "state": {
    "id": "cancelled",
    "desc": "Cancelled"
  },
  "requested_at": "2021-11-30",
  "items": [
    {
      "id": 1,
      "product_id": 1,
      "title": "Blanditiis minima explicabo incidunt ratione mollitia aut aut repellat consequuntur repellendus qui totam voluptatem. (Item)",
      "request_min": 1,
      "unit_price": {
        "value": "689.000",
        "currency": "IQD",
        "formatted": "689 IQD"
      },
      "unit_price_original": {
        "value": "689.000",
        "currency": "IQD",
        "formatted": "689 IQD"
      },
      "total_price": {
        "value": "2756.000",
        "currency": "IQD",
        "formatted": "2,756 IQD"
      },
      "total_quantity": 4,
      "is_deleted": false,
      "is_quantity_available": true
    }
  ],
  "products_price": {
    "value": "2756.000",
    "currency": "IQD",
    "formatted": "2,756 IQD"
  },
  "shipping_costs": {
    "value": "780570.000",
    "currency": "IQD",
    "formatted": "780,570 IQD"
  },
  "promocode_discount_amount": {
    "value": "826.800",
    "currency": "IQD",
    "formatted": "827 IQD"
  },
  "total_amount": {
    "value": "782499.200",
    "currency": "IQD",
    "formatted": "782,499 IQD"
  },
  "usd_iqd_conversion_rate": 1470,
  "total_amount_iqd": {
    "value": "782499.200",
    "currency": "IQD",
    "formatted": "782,499 IQD"
  },
  "shipping_address": {
    "id": 24,
    "coordinates": null,
    "governorate": {
      "id": 1,
      "name": "Baghdad"
    },
    "region_desc": "karah",
    "address": "karah",
    "landmarks": "",
    "building_number": null,
    "mobile": "9647901911601"
  },
  "promocode": {
    "id": 1,
    "status": {
      "id": "active",
      "desc": "Active"
    },
    "code": "EJR5-GPDC",
    "reward": "30 %"
  }
}
*/

  String? id;
  OrderDetailsResponseDataState? state;
  String? requestedAt;
  List<OrderDetailsResponseDataItems>? items;
  OrderDetailsResponseDataProductsPrice? productsPrice;
  OrderDetailsResponseDataShippingCosts? shippingCosts;
  OrderDetailsResponseDataPromocodeDiscountAmount? promocodeDiscountAmount;
  OrderDetailsResponseDataTotalAmount? totalAmount;
  String? usdIqdConversionRate;
  OrderDetailsResponseDataTotalAmountIqd? totalAmountIqd;
  OrderDetailsResponseDataShippingAddress? shippingAddress;
  OrderDetailsResponseDataPromocode? promocode;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponseData({
    this.id,
    this.state,
    this.requestedAt,
    this.items,
    this.productsPrice,
    this.shippingCosts,
    this.promocodeDiscountAmount,
    this.totalAmount,
    this.usdIqdConversionRate,
    this.totalAmountIqd,
    this.shippingAddress,
    this.promocode,
  });
  OrderDetailsResponseData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    state = (json["state"] != null && (json["state"] is Map))
        ? OrderDetailsResponseDataState.fromJson(json["state"])
        : null;
    requestedAt = json["requested_at"]?.toString();
    if (json["items"] != null && (json["items"] is List)) {
      final v = json["items"];
      final arr0 = <OrderDetailsResponseDataItems>[];
      v.forEach((v) {
        arr0.add(OrderDetailsResponseDataItems.fromJson(v));
      });
      items = arr0;
    }
    productsPrice = (json["products_price"] != null &&
            (json["products_price"] is Map))
        ? OrderDetailsResponseDataProductsPrice.fromJson(json["products_price"])
        : null;
    shippingCosts = (json["shipping_costs"] != null &&
            (json["shipping_costs"] is Map))
        ? OrderDetailsResponseDataShippingCosts.fromJson(json["shipping_costs"])
        : null;
    promocodeDiscountAmount = (json["promocode_discount_amount"] != null &&
            (json["promocode_discount_amount"] is Map))
        ? OrderDetailsResponseDataPromocodeDiscountAmount.fromJson(
            json["promocode_discount_amount"])
        : null;
    totalAmount =
        (json["total_amount"] != null && (json["total_amount"] is Map))
            ? OrderDetailsResponseDataTotalAmount.fromJson(json["total_amount"])
            : null;
    usdIqdConversionRate = json["usd_iqd_conversion_rate"]?.toString();
    totalAmountIqd =
        (json["total_amount_iqd"] != null && (json["total_amount_iqd"] is Map))
            ? OrderDetailsResponseDataTotalAmountIqd.fromJson(
                json["total_amount_iqd"])
            : null;
    shippingAddress =
        (json["shipping_address"] != null && (json["shipping_address"] is Map))
            ? OrderDetailsResponseDataShippingAddress.fromJson(
                json["shipping_address"])
            : null;
    promocode = (json["promocode"] != null && (json["promocode"] is Map))
        ? OrderDetailsResponseDataPromocode.fromJson(json["promocode"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (state != null) {
      data["state"] = state!.toJson();
    }
    data["requested_at"] = requestedAt;
    if (items != null) {
      final v = items;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v.toJson());
      });
      data["items"] = arr0;
    }
    if (productsPrice != null) {
      data["products_price"] = productsPrice!.toJson();
    }
    if (shippingCosts != null) {
      data["shipping_costs"] = shippingCosts!.toJson();
    }
    if (promocodeDiscountAmount != null) {
      data["promocode_discount_amount"] = promocodeDiscountAmount!.toJson();
    }
    if (totalAmount != null) {
      data["total_amount"] = totalAmount!.toJson();
    }
    data["usd_iqd_conversion_rate"] = usdIqdConversionRate;
    if (totalAmountIqd != null) {
      data["total_amount_iqd"] = totalAmountIqd!.toJson();
    }
    if (shippingAddress != null) {
      data["shipping_address"] = shippingAddress!.toJson();
    }
    if (promocode != null) {
      data["promocode"] = promocode!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class OrderDetailsResponse {
/*
{
  "data": {
    "id": 1,
    "state": {
      "id": "cancelled",
      "desc": "Cancelled"
    },
    "requested_at": "2021-11-30",
    "items": [
      {
        "id": 1,
        "product_id": 1,
        "title": "Blanditiis minima explicabo incidunt ratione mollitia aut aut repellat consequuntur repellendus qui totam voluptatem. (Item)",
        "request_min": 1,
        "unit_price": {
          "value": "689.000",
          "currency": "IQD",
          "formatted": "689 IQD"
        },
        "unit_price_original": {
          "value": "689.000",
          "currency": "IQD",
          "formatted": "689 IQD"
        },
        "total_price": {
          "value": "2756.000",
          "currency": "IQD",
          "formatted": "2,756 IQD"
        },
        "total_quantity": 4,
        "is_deleted": false,
        "is_quantity_available": true
      }
    ],
    "products_price": {
      "value": "2756.000",
      "currency": "IQD",
      "formatted": "2,756 IQD"
    },
    "shipping_costs": {
      "value": "780570.000",
      "currency": "IQD",
      "formatted": "780,570 IQD"
    },
    "promocode_discount_amount": {
      "value": "826.800",
      "currency": "IQD",
      "formatted": "827 IQD"
    },
    "total_amount": {
      "value": "782499.200",
      "currency": "IQD",
      "formatted": "782,499 IQD"
    },
    "usd_iqd_conversion_rate": 1470,
    "total_amount_iqd": {
      "value": "782499.200",
      "currency": "IQD",
      "formatted": "782,499 IQD"
    },
    "shipping_address": {
      "id": 24,
      "coordinates": null,
      "governorate": {
        "id": 1,
        "name": "Baghdad"
      },
      "region_desc": "karah",
      "address": "karah",
      "landmarks": "",
      "building_number": null,
      "mobile": "9647901911601"
    },
    "promocode": {
      "id": 1,
      "status": {
        "id": "active",
        "desc": "Active"
      },
      "code": "EJR5-GPDC",
      "reward": "30 %"
    }
  }
}
*/

  OrderDetailsResponseData? data;
  Map<String, dynamic> __origJson = {};

  OrderDetailsResponse({
    this.data,
  });
  OrderDetailsResponse.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    data = (json["data"] != null && (json["data"] is Map))
        ? OrderDetailsResponseData.fromJson(json["data"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
