///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RemindersResponseData {
/*
{
  "id": 1,
  "text": "Cum iste enim aut est eum quasi minima. Molestias rerum optio quaerat mollitia consequatur illo et facere. Repellendus illum tenetur nihil.",
  "send_at": "2022-01-25 06:50 pm"
}
*/

  String? id;
  String? text;
  String? sendAt;
  Map<String, dynamic> __origJson = {};

  RemindersResponseData({
    this.id,
    this.text,
    this.sendAt,
  });
  RemindersResponseData.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    id = json["id"]?.toString();
    text = json["text"]?.toString();
    sendAt = json["send_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["text"] = text;
    data["send_at"] = sendAt;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}

class RemindersResponse {
/*
{
  "data": [
    {
      "id": 1,
      "text": "Cum iste enim aut est eum quasi minima. Molestias rerum optio quaerat mollitia consequatur illo et facere. Repellendus illum tenetur nihil.",
      "send_at": "2022-01-25 06:50 pm"
    }
  ]
}
*/

  List<RemindersResponseData?>? data;
  Map<String, dynamic> __origJson = {};

  RemindersResponse({
    this.data,
  });
  RemindersResponse.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    if (json["data"] != null && (json["data"] is List)) {
      final v = json["data"];
      final arr0 = <RemindersResponseData>[];
      v.forEach((v) {
        arr0.add(RemindersResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
